-- Docentes (lista completa)
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('AGUAYO MENDEZ', 'FRAY MARTIN', 'tup-d1624@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('AGUILAR ESCAMILLA', 'JESUS ALFONSO', 'tup-d1389@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ALAMILLA', 'MARCEL', 'tup-d1120@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ALCANTARA VELAZQUEZ JOSE', 'DE JESUS', 'tup-d1800@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ALCOCER REYES', 'JOSE JAHIR', 'tup-d1107@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ALMANZA POOL', 'MIGUEL ANGEL', 'tup-d1584@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ALVARADO', 'VALENCIA CRISTHIAN', 'tup-d1207@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('AMEZCUA', 'SANCHEZ JORDANA', 'tup-d1230@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ANGEL GALEANA', 'DULCE MARIA', 'tup-d1572@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ANGEL GALEANA', 'MARCO ANTONIO', 'tup-d1503@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ANTONIO', 'LOPEZ NOHE', 'tup-d1419@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ARANDA HANSMANN BLANCA', 'MARIA TERESA', 'tup-d1416@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ARAUJO GONZÁLEZ', 'NATALIA BELEN', 'tup-d1578@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ARIAS LOPEZ', 'IRMA VANESSA', 'tup-d1602@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ARROYO', 'GALLEGOS DAVID', 'tup-d1098@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ARTEAGA VILLAVICENCIO', 'MARINA ISABEL', 'tup-d1631@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('BALLINAS', 'BARRIOS JOSUE', 'tup-d1575@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('BALTAZAR CRISTOBAL', 'BRENDA VICTORIANA', 'tup-d1502@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('BATUN MAY', 'JESSICA YOSELIN', 'tup-d1601@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('BELTRAN', 'DIAZ MARGARITA', 'tup-d1625@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('BONETE', 'MACAYA ARANZAZU', 'tup-d1579@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('BRAVO CASTAÑEDA', 'YESSICA LIZBETH', 'tup-d1385@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('BURGOS MAGAÑA', 'JEANNIE ARANTXA', 'tup-d1394@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CABRERA', 'BUSTAMANTE FERNANDA', 'tup-d1528@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CAHUM DZUL MARY', 'DEL CARMEN', 'tup-d1423@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CANCHE SANSORES', 'JESSICA ISABEL', 'tup-d1210@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CANELA VALLE', 'JOSE LUIS', 'tup-d1628@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CARBAJAL HEREDIA', 'PEDRO RUBEN', 'tup-d1072@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CARDENAS HERNANDEZ', 'RUTH MONSERRAT', 'tup-d1415@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CARVALLO ORTIZ', 'GEORGINA MARIA', 'tup-d1223@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CASAS GUTIERREZ', 'KARINA MAYELA', 'tup-d1792@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CASAS GUTIERREZ', 'KARMINA BERENIZ', 'tup-d1793@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CASTILLO GUTIERREZ', 'DAVID ENRIQUE', 'tup-d1378@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CASTRO', 'CRUZ GILBERTO', 'tup-d1132@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CASTRO', 'JIMENES MAURICIO', 'tup-d1616@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CERVANTES ORTIZ', 'VICTOR MANUEL', 'tup-d1301@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CETINA CHAN', 'AMAIRANY GUADALUPE', 'tup-d1373@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CHAN AGUILAR', 'RAUL IÑAKI', 'tup-d444@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CHAN', 'SANCHEZ NAYELY', 'tup-d1086@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CHAN SUAREZ', 'FRANCISCO JAVIER', 'tup-d1391@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CHAPA NAVA', 'MARIA GUADALUPE', 'tup-d160@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CHAVARRIA', 'MORALES ARMANDO', 'tup-d81@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CHEL PECH', 'VIVIANA BEATRIZ', '--', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CITUK CAUICH', 'PEDRO CARLOS', 'tup-d1101@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CLEMENTE', 'MARTINEZ MARIA', 'tup-d1552@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('COCOM', 'UUH LUCIANO', 'tup-d17@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('COLLI', 'FUENTES CITLALLY', 'tup-d1506@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CONRADO MOGUEL', 'DANIEL GUILLERMO', 'tup-d1635@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CORAL AVILA GELMAN', 'DE JESUS', 'tup-d150@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CORNELIO', 'VAZQUEZ ZULEIMA', 'tup-d1189@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CORTÁZAR MONTERO', 'LUIS ANGEL', 'tup-d1586@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CORZO MENDEZ', 'EVELYN YASARETH', 'tup-d1082@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CRUZ', 'MARTINEZ GENOVEVA', 'tup-d202@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CRUZ', 'VAZQUEZ EDUARDO', 'tup-d1686@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DE LEON', 'MELENDEZ AMAIRANI', 'tup-d113@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DELGADO RAMIREZ', 'JOSUE ARMANDO', 'tup-d1144@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DELOYA', 'BELLO JESUS', 'tup-d1629@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DIAZ CHALE', 'HAFID ALEJANDRO', 'tup-d1372@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DOMINGUEZ', 'CASAUX JUAN', 'tup-d1435@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DOMINGUEZ ESPEJO JHOANA', 'DEL ROCIO', 'tup-d1214@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DOMINGUEZ PACHECO', 'PEDRO BALOY', 'tup-d1368@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DZUL ITZAH', 'NIDIA GUADALUPE', 'tup-d94@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ESCALONA CRUZ', 'CRISTI JANET', 'tup-d117@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ESCALONA', 'CRUZ KARINA', 'tup-d153@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ESCOTO VARELA', 'DANIEL JOSEPH', 'tup-d1621@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ESPINAL DIAZ', 'ROBERTO ALONSO', 'tup-d1797@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('FARIAS DÍAS', 'CLAUDIO JOSÉ', 'tup-d1405@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('FLOTA GARIBAY', 'ELBERTH ABEL', 'tup-d1412@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GALICIA PARRA', 'JUAN MANUEL', 'tup-d28@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GALLO ESCARCIA', 'DIANA VIANEY', 'tup-d1639@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GARCIA DIAZ', 'CELIA FARIDE', 'tup-d1600@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GARCIA LUNA', 'BAEZA HUMBERTO', 'tup-d1644@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GARRIDO POSADAS', 'JOSE ALBERTO', 'tup-d1617@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GONZALEZ CARDENAS', 'VICTOR MANUEL', 'tup-d1034@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GONZALEZ MONTE', 'JOSUE TOMAS', 'tup-d1564@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GONZÁLEZ', 'YÁÑEZ YESENIA', 'tup-d1505@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GORDILLO MANZO', 'CORIANTUMR JAFET', 'tup-d1519@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GORDON PALACIOS', 'LUZ ENEIDA', 'tup-d1546@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GUILLEN VELAZQUEZ', 'ISRAEL ABRAHAM', 'tup-d1798@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GUTIERREZ CORTEZ', 'JAVIER YOVANI', 'tup-d1619@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GUTIERREZ DIAZ', 'ERIKA DANIELA', 'tup-d1544@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HAU ONTIVEROS', 'MIRIAM CECILIA', 'tup-d1384@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HERNANDEZ HERNANDEZ', 'ROBERTO ABRAHAM', 'tup-d1795@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HERNANDEZ', 'OLIVERA VANESSA', 'tup-d1688@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HOIL BOBADILLA', 'INGRID YIDELI', 'tup-d125@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HUCHIM CHI', 'RUSSEL MANUEL', 'tup-d1622@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('IBAÑEZ PARAMO', 'CARLOS SHARICK', 'tup-d1623@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('JAIMES', 'MENDEZ ROBERTO', 'tup-d1049@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('JASSO RODRIGUEZ', 'SHANTAL PATRICIA', 'tup-d1156@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('JIMENEZ BALLESTEROS', 'KAREN AIDEE', 'tup-d1501@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('JIMENEZ SIERRA', 'OLIVER ALAIN', 'tup-d1030@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('KOH', 'KOH AVRIL', 'tup-d1157@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('LANDERO RAMIREZ ROXANA', 'DEL CARMEN', 'tup-d158@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('LEÓN GARCÍA', 'VICTOR GUADALUPE', 'tup-d1632@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('LOEZA PECH', 'DEYSI RAQUEL', 'tup-d1594@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('LOPEZ', 'LEYVA ROSENDA', 'tup-d42@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('LORIA LOPEZ', 'SHEILA DARANI', 'tup-d1576@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('AGUILAR', 'VALENZUELA MANUEL', 'tup-d1332@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARCIAL MAGDALENO', 'ANA KAREN', 'tup-d1569@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARTHA VERÓNICA', 'HUERTA MEDINA', 'tup-d1395@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARTÍN PECH', 'LIZBETH JANET', 'tup-d1647@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARTINEZ BADILLO', 'LUISA AURORA', 'tup-d1565@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARTINEZ LARA', 'MARCO ANTONIO', 'tup-d116@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MELENDEZ ZARATE', 'JENYFER CARIME', 'tup-d1173@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MENCHACA ALONSO RUTH', 'DEL CARMEN', 'tup-d1047@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MENDOZA MORENO', 'MONICA LUBIN', 'tup-d1518@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MENESES BRAGA', 'MANUEL JESUS', 'tup-d1510@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MIGUEL', 'HERNANDEZ RUTH', 'tup-d1571@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MIRANDA', 'ROBLES ÓSCAR', 'tup-d1636@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MONTAÑO GOMEZ', 'ROSA ELVIA', 'tup-d1500@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MONTEMAYOR GONZÁLEZ', 'JOSÉ LUIS', 'tup-d1634@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MORALES GOMEZ', 'KARLA ELVIRA', 'tup-d1593@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('NAVA', 'LEONARDO', 'tup-d1526@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('NEYRA', 'BRITO REBECA', 'tup-d1532@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('OROZCO SALCEDO', 'ABRIL SAKNYCTE', 'tup-d1587@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ORTIZ ANTILLON', 'ANA NOEMI', 'tup-d1787@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ORTIZ PEREZ', 'MILDRED YARELY', 'tup-d1613@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('OYOSA SANTIN', 'BRANDON BALDEMAR', 'tup-d1790@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PACHECO', 'OJEDA BEATRIZ', 'tup-d1515@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PALACIOS ORTIZ', 'THALIA ESTEFANI', 'tup-d1414@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PALMA PACHECO MARGARITA', 'DEL ROSARIO', 'tup-d1567@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PALOMO', 'AGUILAR DANIELA', 'tup-1597@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PATIÑO SANTIAGO', 'MARIA GUADALUPE', 'tup-d1160@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PERAZA', 'MANJARREZ JULIETA', 'tup-d1018@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ DE LA', 'CRUZ ITZEL', 'tup-d1580@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ DOMINGUEZ', 'ALMA ISABEL', 'tup-d1432@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ GALLEGOS', 'LUIS MIGUEL', 'tup-d1509@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ RAMIREZ', 'HECTOR LEONEL', 'tup-d1529@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ RODRIGUEZ', 'ALICIA YASURY', 'tup-d1627@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ', 'SAAVEDRA DANIEL', 'tup-d1524@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ SOLIS', 'MARLON SAUL', 'tup-d1431@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PÉREZ ZETINA', 'MIGUEL ANGEL', 'tup-d1473@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PONCE', 'ALVAREZ IVAN', 'tup-d1653@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PONCE GARCIA', 'KARLA YELITZA', 'tup-d1212@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('POOL ROBLES', 'JOSE GONZALO', 'tup-d1164@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('POOT COLLI', 'KARLA ALEJANDRA', 'tup-d1475@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('QUERO ALEGRIA', 'DAVID ROBERTO', 'tup-d1511@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RAMIREZ TORRES MA.', 'DEL ROSARIO', 'tup-d1179@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RAMIREZ ZAPATA', 'JOSE F.', 'tup-d1591@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('REA VARGAS', 'FEDRA HELENA', 'tup-d61@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('REYES HERNANDEZ', 'TILA VIRGINIA', 'tup-d1355@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('REYES', 'ISLAS MARIBEL', 'tup-d1689@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('REYES SANTOS', 'OSCAR JOSE', 'tup-d1202@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('REYES', 'TRONCO ANDREA', 'tup-d1630@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RIOS', 'CRUZ YESSICA', 'tup-d1595@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RIOS RODRIGUEZ', 'EMMA LAURA', 'tup-d1598@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RIOS RODRIGUEZ', 'MARIA JOSE', 'tup-d1150@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RISUEÑO AVILES', 'IVAN AMBROCIO', 'tup-d1566@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ROCHA OSORNIO', 'MONICA ELIZABETH', 'tup-d1411@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ROJAS', 'CRUZ ORLANDO', 'tup-d1403@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ROJAS', 'MADRID ADRIANA', 'tup-d1648@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ROSARIO SOSA', 'JORGE ALBERTO', 'tup-d1126@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ROSAS RAMOS', 'YAEL ALEJANDRO', 'tup-d791@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RUIZ MARTINEZ', 'PEDRO ANTONIO', 'tup-d1614@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SALAS PAT', 'RUBY GRISELL', 'tup-d101@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SANCHEZ AVALOS', 'MARIA ELENA', 'tup-d1533@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SANCHEZ BLANCO', 'ANGEL SALVADOR', 'tup-d1178@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SANCHEZ CHAVEZ', 'IRMA ARACELI', 'tup-d1590@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SANCHEZ DE DIOS', 'DEMI NAOMI', 'tup-d1574@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SAYAS PALMERO', 'BRIAN LEONARDO', 'tup-d1149@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SCIANGULA', 'LIDA RUTH', 'tup-d1513@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SEGURA', 'TRINIDAD RAÚL', 'tup-d1645@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SEVILLA AGUILAR', 'LAURA AMERICA', 'tup-d1205@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SEVILLA RAMÍREZ', 'MARÍA YESENIA', 'tup-d1520@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SILVA', 'LEÓN ÁNGEL', 'tup-d1643@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SILVA MENDEZ', 'JHOSELIN VIRIDIANA', 'tup-d1649@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SOSA NOVELO', 'JANETH BEATRIZ', 'tup-d1185@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SUAREZ PISTE', 'MAGALY ALEJANDRA', 'tup-d1568@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SUSTAITA', 'MENDOZA JONATHAN', 'tup-d1637@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('TORRES CERVERA', 'EDDY YOVAN', 'tup-d1380@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('TORRES MADRID', 'PALACIOS OSWALDO', 'tup-d1626@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('TREVIÑO TREVIÑO', 'SANDRA LUZ', 'tup-d1589@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('TRUJEQUE PARRA', 'MANUEL JESUS', 'tup-d1534@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('TUN', 'CASTILLO LUCILA', 'tup-d1609@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('TUN LOPEZ', 'ELSY AMALIA', 'tup-d1381@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('UC ARCE', 'MAYRA OLIVETT', 'tup-d1548@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('UC CIAU', 'JOSE ANTONIO', 'tup-d95@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('UC KUYOC', 'FELIPE SANTIAGO', 'tup-d1026@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('UICAB MALDONADO', 'METZLI NATALI', 'tup-d1547@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ULIN AGUSTINIANO', 'LUIS ANGEL', 'tup-d1791@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('VAZQUEZ CHABLE JARED', 'VAZQUEZ CHABLE', 'tup-d1577@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('VAZQUEZ FLORES', 'MARLON FERMIN', 'tup-d1527@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('VÁZQUEZ GUTIERREZ', 'LUIS ROBERTO', 'tup-d1646@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('VEGA', 'JIMÉNEZ JUDITH', 'tup-d1642@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('VEGA ROYERO', 'ZOLANDA PATRICIA', 'tup-d1147@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('VELAZQUEZ VAZQUEZ', 'SOFIA MONZERRAT', 'tup-d1379@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('VERGARA CASTRO', 'VERONICA TERESA', 'tup-d809@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ZAVALA SALVADOR', 'DENNYS ELIZABETH', 'tup-d1603@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GONZALEZ RODRIGUEZ', 'MYRIAM ANAHÍ', 'tup-d1654@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('LOPEZ CANTILLO', 'RAUL FERNANDO', 'tup-d1796@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HERNANDEZ MIRANDA GRISELL', 'DEL CARMEN', 'tup-d1656@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PRECIADO HERRERA', 'LEONARDO JAVIER', 'tup-d1657@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CEL NAAL', 'NOE ISAAC', 'noeisaac.cel@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ALOR GARCIA', 'LIZETH ELLIANE', 'tup-d1660@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('NAH ROSADO', 'ORIANA AMAYRANI', 'tup-d1153@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RAMOS LEDEZMA', 'ISRRAEL RODOLFO', 'tup-d1659@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ZAVALA', 'HERNANDEZ JOEL', 'tup-d1663@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ESPINOSA', 'MARQUEZ BERENICE', 'algo@algo.com', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DE LOS SANTOS CAMPO SECO', 'SERGIO ENRIQUE', 'sergio.santos@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('VEGA GONGORA', 'OMAR ENRIQUE', 'tup-d1664@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CAÑIVE', 'RODRIGUEZ YAIMA', 'tup-d1666@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HEDDING RODRIGUEZ', 'ALEJANDRA BERENICE', 'tup-d1667@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DIAZ CARRILLO', 'MELINA ABRIL', 'tup-d1669@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Alvarez Tostado', 'Archundia Gerardo', 'tup-dalvarez@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GONZALEZ CARDENAS', 'JOSE GABRIEL', 'tup-d1665@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MAYA CALVO', 'CARLOS CESAR', 'tup-d1679@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RODRIGUEZ', 'GARCIA MAXIMILIANO', 'tup-d1037@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('VICENTE MARTIN', 'MARIA TERESA', 'tup-d1678@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CRUZ', 'MORENO CRISPIN', 'tup-d1676@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RODRIGUEZ', 'SOSA ARVIN', 'tup-d1677@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DIAZ CAUICH', 'PATRICIO ALEXANDER', 'tup-d1675@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GUTIERREZ FLORES', 'ROBERTO CARLOS', 'tup-d1672@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ORDOÑES COELLO', 'DULCE VALERIA', 'tup-d1673@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CHACON SOSA', 'ANGELES AZUCENA', 'tup-d1393@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARTINEZ SONI', 'RODOLFO GABRIEL', 'tup-d1668@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('OCAMPO', 'VAZQUEZ ABEL', 'tup-d1671@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SANTOS CUMI', 'FARITH AZAEL', 'tup-d1670@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('AGUILAR SANCHEZ', 'MARIO ALBERTO', 'tup-d1680@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Cervantes', 'Cervantes Margarita', 'tup-d3000@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MEDINA AKE', 'MARIO MANUEL', 'tup-d109@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DIAZ VENTURA', 'JANNET ARACELY', 'tup-d1683@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GARCIA  TORRES', 'INGRID AMAIRANI', 'tup-d1397@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARFIL GOMEZ ', 'WILLY EFREN', 'tup-d1682@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ROCHE CANTO', 'CINTHIA MARIA', 'tup-d1674@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HERNANDEZ', 'JIMENEZ ERIKA', 'tup-d1685@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DE LA CRUZ', 'GOMEZ MAYIBE', 'tup-d1681@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('EJEMPLO', 'SISTEMAS DOCENTE', 'docente.ejemplo@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ALONSO HERNANDEZ', 'ANA SOFIA', 'tup-d1691@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CATZIM PAT', 'OSCAR DAVID', 'tup-d185@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('VAZQUEZ VELAZQUEZ NAYANCI', 'DEL ROSARIO', 'tup-d1692@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('VARGAS MILLAN', 'NAYELY GUADALUPE', 'tup-d1693@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SALAZAR GOMEZ', 'BRISA PALOMA', 'tup-d1694@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CRUZ PARDO', 'JESUS MANUEL', 'tup-d1684@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ORDOÑEZ', 'CRUZ LESLY', 'tup-d1695@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GUERRA', 'GONZALEZ VICTORIA', 'tup-d1696@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('FRIAS VENTURA', 'ARMANDO JACOB', 'tup-d1697@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GARCIA MURGUIA', 'JOSE ELGAR', 'tup-d1698@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MURRIETA PADILLA', 'ARTURO JONATHAN', 'tup-d1699@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('FAJARDO GONZALEZ', 'ISRAEL JESREEL', 'tup-d1700@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SANTILLAN', 'MACEDO SANDRA', 'tup-d1701@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('NOH ABAN', 'OSCAR OLIVER', 'tup-d1794@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GALERA POOL', 'BRICER ISMAR', 'tup-d1507@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SANCHEZ LÓPEZ', 'NAYELI MONSERRAT', 'tup-d1703@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARQUEZ ALAMILLA', 'DANIELA GEORGINA', 'tup-d1704@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PUERTOS', 'PEÑA RUBEN', 'tup-d1706@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CARBALLO QUINTANA', 'EDGAR FEDERICO', 'tup-d1426@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('VAZQUEZ', 'CHABLE JARED', 'tup-d1708@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HERRERA', 'RODRIGUEZ JESSICA', 'tup-d1707@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HERNANDEZ BAILON', 'JULIO CESAR', 'tup-d1709@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GARCIA  MARTIR', 'MAYRA ISABEL', 'tup-d1710@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MEDINA NOH', 'LAURA GISSELY', 'tup-d1711@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('TRUJILLO BONIFAZ', 'PROF.-YESUA YAIR', 'tup-d1712@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HERNANDEZ MENDOZA', 'ROBERTO ANDRES', 'tup-d1713@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PIÑA VALLE', 'ANDREA S.', 'tup-d1714@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MEDINA SERNA TERESITA', 'DE JESUS', 'tup-d1386@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('FERNANDEZ VELA', ' NATALIA', 'tup-d1143@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CERVERA HERRERA', 'IRVING JESUS', 'tup-d97@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SUAREZ NOVELO', 'MARIA ELIZABETH', 'tup-d1050@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SHIELDS MUÑOZ', 'LUIS RODOLFO', 'tup-d1716@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ALCOCER URBIETA', 'LEYDI JACQUELIN', 'tup-d1715@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('LUEVANO GONZALEZ', 'JOSE BENJAMÍN', 'tup-d1718@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('LOPEZ OSORIO', 'BEATRIZ ADRIANA', 'tup-d1719@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('JUAREZ', 'LLOVERA ARMANDO', 'tup-d1720@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('REYES', 'GARCIA JESSICA', 'tup-d1721@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('OCAMPO', 'CAMPOS MAURICIO', 'tup-d1516@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CASTILLO', 'OLASCOAGA TERESA', 'tup-d1729@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARTIN POMPEYO', ' NELSON', 'tup-d1730@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MEX KANTUN', 'DANIEL JESUS', 'tup-d1735@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARTINEZ', 'MARTINEZ PROF.-MARICARMEN', 'tup-d1737@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CHAVEZ  MENDOZA', 'MIGUEL ALEJANDRO', 'tup-d15@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MEDINA NOH', 'ADRIANA JACQUELINE', 'tup-d1723@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('XOOL VALDEZ', 'ANGEL JOSUE', 'tup-d1727@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MORALES', 'GARCIA VALERIA', 'tup-d1724@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ PALACIOS', 'JONATHAN ALEXIS', 'tup-d1734@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ARCOS ', 'DIAZ ANACELI', 'tup-d1728@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SAAVEDRA BELLO', 'ANGEL IVAN', 'tup-d1725@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PARRA LORIAS', 'FRANCIS YOHARA', 'tup-d1736@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MUKUL CAAMAL', 'MELISSA LISSET', 'tup-d1732@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MAVIL MORALES', 'VALERIA IXIHU', 'tup-d1731@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HERNANDEZ  MORALES', 'JESUS ALBERTO', 'tup-d1726@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CORAL PASOS', 'GRECIA MONSERRAT', 'tup-d1733@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CAMPOSECO', 'MENDOZA MARCOS', 'tup-d1738@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('TOVAR  BERROS', 'JOSEFA DAPHNE', 'tup-d1739@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ROMERO RIOS ', 'PROF.-LEYDI ROXANA', 'tup-d1740@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('FLORES DURAN', 'PAOLA ESTEFANIA', 'tup-d1748@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ALONSO  MONTOYA', 'LUIS ANTONIO', 'tup-d1749@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MEGCHUN CRUZ', 'JOAN OSVALDO', 'tup-d1743@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ PROF.-', 'JUAN FRANCISCO', 'tup-d1750@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('YEH CAAMAL', 'MARIA ALICIA', 'tup-d1751@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SABIDO  PARRA', 'SAMANTA JAZMIN', 'tup-d1744@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CANTOR  GONZALEZ ', 'LUIGELMI DEYANIRA', 'tup-d1745@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ALMEIDA RODRIGUEZ', 'KATIA MICHEL', 'tup-d1522@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ EDGAR', 'DANIELA AURORA', 'tup-d1753@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PRADO', 'HIGAREDA ANDREA', 'tup-d1752@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HERNÁNDEZ', 'ZAVALETA GABRIELA', 'tup-d1755@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARTINEZ NUÑEZ MAGDALENA', 'DEL CARMEN', 'tup-d1759@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('AGUIRRE RODRIGUEZ', 'DENISSE YADIRA', 'tup-d1760@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CARMONA', 'ASCENCION FRANCISCO', 'tup-d1761@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GUADARRAMA', 'GOMEZ IRMA', 'tup-d1762@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('LIMON  FLORES', 'MARIELA AZENHED', 'tup-d1766@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Jimenez  Martinez', 'Guadalupe Joselinne', 'tup-d1757@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('QUIROZ RIOS', 'RUBEN DARIO', 'tup-d1765@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MEDINA  BASULTO  MARIA DE', 'LOS ANGELES', 'tup-d1758@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('LOPEZ  OVANDO', ' HAMID', 'tup-d1763@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SOTO ARIAS', 'CARLOS EDUARDO', 'tup-d1764@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CASANOVA GAMBOA', 'WILBERT HUMBERTO', 'tup-d1769@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RUIZ  DURAN', 'JOANA ALEJANDRA', 'tup-d1768@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ALVAREZ LUNA', 'LUIS MIGUEL', 'tup-d1771@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RODRIGUEZ  CHACON', 'BRENDA CELESTE', 'tup-d1770@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MAY GONGORA', 'JUAN CARLOS', 'tup-d1772@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ MENDOZA', 'ULISES ALEJANDRO', 'tup-d1773@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Velazquez  Mondragon', ' Sandra', 'tup-d1774@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SANCHEZ', 'RODRIGUEZ OMAR', 'tup-d1775@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ESPINOSA', 'MARTINEZ ALEJANDRA', 'tup-d1767@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ANCONA PAYAS', 'LUIS MATEO', 'tup-d1777@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RIVERA', 'CASTREJON ITZIA', 'tup-d1776@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GUZMAN', 'MUÑOZ FABIOLA', 'tup-d1778@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Alvarez', 'Huerta Enrique', 'tup-d1779@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SHOMAR', 'GALICIA ISRAEL', 'tup-d1756@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SANCHEZ ', 'RODRIGUEZ MIGUEL', 'tup-d1780@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MAGALLÓN CABRERA', 'ALBERTO ALFONSO', 'tup-d1781@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ALVAREZ JACINTO', 'LUIS ELEACIBT', 'tup-d1782@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MORENO', 'ALZATE BRENDA', 'tup-d1783@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ARIAS GONZALEZ', 'FRANCA ALEJANDRA', 'tup-d1784@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GOMEZ LAGUNAS', 'ROCIO JANNET', 'tup-d1785@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CRUZ  RETANA', 'LILIAN MAGHALY', 'tup-d1786@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MONTERO CEME ALBERTO', 'DE JESUS', 'tup-d1409@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('TREJO ', 'ROCHA ALEJANDRO', 'tup-d1799@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DE LEON BENITEZ ', 'MARIA ROSALINA', 'tup-d1802@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CAUICH  TORRES', 'MIGUEL ALEJANDRO', 'tup-d1801@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ZARAGOZA', 'CHE JOSUE', 'tup-d1806@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('COFFIN ', 'JIMENEZ MARISOL', 'tup-d1807@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GUTIERREZ TRUEBA', 'JORGE ALBERTO', 'tup-d1803@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ARGUELLO AZPURUA', 'MARYORIE GERALDINE', 'tup-d1804@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('LUNA', 'VILLALOBOS ELIZABETH', 'tup-d1788@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CARDENAS', 'MONTEMAYOR ALEXANDRA', 'tup-d1789@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MORALES MONTAÑO', 'EVELIN MAYANIN', 'tup-d1805@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MELCHOR URIBE  MARIA', 'DEL ROCIO', 'tup-d1808@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MENDEZ', 'IZQUIERDO GUADALUPE', 'tup-d1809@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Gonzalez Requena', 'Amy Camila', 'tup-dajedrez@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PUENTES', 'AGUIRRE JESUS', 'tup-d1810@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
