-- Solo 72 docentes que imparten clases (Reporte_clases)
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Marco Antonio', 'Martinez Lara', 'tup-d116@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Lucila', 'Tun Castillo', 'tup-d1609@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Shantal Patricia', 'Jasso Rodriguez', 'tup-d1156@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Jose Gabriel', 'Gonzalez Cardenas', 'tup-d1665@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Brenda', 'Moreno Alzate', 'tup-d1783@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Armando', 'Chavarria Morales', 'tup-d81@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Leydi Jacquelin', 'Alcocer Urbieta', 'tup-d1715@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Miguel', 'Sanchez Rodriguez', 'tup-d1780@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Victor Manuel', 'Gonzalez Cardenas', 'tup-d1665@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Lesly', 'Ordoñez Cruz', 'tup-d1695@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Lizbeth Janet', 'Martín Pech', 'tup-d1647@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Alma Isabel', 'Perez Dominguez', 'tup-d1432@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Javier Yovani', 'Gutierrez Cortez', 'tup-d1619@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Josue Tomas', 'Gonzalez Monte', 'tup-d1564@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Jorge Alberto', 'Rosario Sosa', 'tup-d1126@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Rocio Jannet', 'Gomez Lagunas', 'tup-d1785@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Ana Noemi', 'Ortiz Antillon', 'tup-d1787@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Yaima', 'Cañive Rodriguez', 'tup-d1666@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Jose Alberto', 'Garrido Posadas', 'tup-d1617@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Maria Guadalupe', 'Patiño Santiago', 'tup-d1160@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Franca Alejandra', 'Arias Gonzalez', 'tup-d1784@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Maryorie Geraldine', 'Arguello Azpurua', 'tup-d1804@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Nidia Guadalupe', 'Dzul Itzah', 'tup-d94@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Georgina Maria', 'Carvallo Ortiz', 'tup-d1223@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Victor Guadalupe', 'León García', 'tup-d1632@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Dios Demi Naomi', 'Sanchez De', 'tup-d1574@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Wilbert Humberto', 'Casanova Gamboa', 'tup-d1769@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Jesus', 'Puentes Aguirre', 'tup-d1810@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Jose Luis', 'Canela Valle', 'tup-d1628@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('José Luis', 'Montemayor González', 'tup-d1634@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Daniel', 'Perez Saavedra', 'tup-d1524@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Andrea', 'Prado Higareda', 'tup-d1752@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Daniela Georgina', 'Marquez Alamilla', 'tup-d1704@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Daniela Aurora', 'Perez Edgar', 'tup-d1753@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Alejandra Berenice', 'Hedding Rodriguez', 'tup-d1667@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Jose Gonzalo', 'Pool Robles', 'tup-d1164@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Israel Jesreel', 'Fajardo Gonzalez', 'tup-d1700@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Juan Francisco', 'Perez Prof.-', 'tup-d1750@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Willy Efren', 'Marfil Gomez', 'tup-d1682@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Farith Azael', 'Santos Cumi', 'tup-d1670@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Hector Leonel', 'Perez Ramirez', 'tup-d1529@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Armando Jacob', 'Frias Ventura', 'tup-d1697@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Dennys Elizabeth', 'Zavala Salvador', 'tup-d1603@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Nohe', 'Antonio Lopez', 'tup-d1419@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Juan Carlos', 'May Gongora', 'tup-d1772@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Ángel', 'Silva León', 'tup-d1643@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Andrea S.', 'Piña Valle', 'tup-d1714@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Maria', 'Clemente Martinez', 'tup-d1552@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Blanca Maria Teresa', 'Aranda Hansmann', 'tup-d1416@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Luis Miguel', 'Perez Gallegos', 'tup-d1509@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Guadalupe', 'Mendez Izquierdo', 'tup-d1809@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Luis Roberto', 'Vázquez Gutierrez', 'tup-d1646@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Julio Cesar', 'Hernandez Bailon', 'tup-d1709@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Daniel Joseph', 'Escoto Varela', 'tup-d1621@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Elberth Abel', 'Flota Garibay', 'tup-d1412@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Carlos Sharick', 'Ibañez Paramo', 'tup-d1623@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Yessica Lizbeth', 'Bravo Castañeda', 'tup-d1385@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Leonardo Javier', 'Preciado Herrera', 'tup-d1657@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Pedro Antonio', 'Ruiz Martinez', 'tup-d1614@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Oscar David', 'Catzim Pat', 'tup-d185@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Miguel Alejandro', 'Chavez Mendoza', 'tup-d15@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Maria Jose', 'Rios Rodriguez', 'tup-d1150@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Ruth Monserrat', 'Cardenas Hernandez', 'tup-d1415@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Oliver Alain', 'Jimenez Sierra', 'tup-d1030@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Cruz Gomez Mayibe', 'De La', 'tup-d1681@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Rosa Elvia', 'Montaño Gomez', 'tup-d1500@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Nayely', 'Chan Sanchez', 'tup-d1086@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Grisell Del Carmen', 'Hernandez Miranda', 'tup-d1656@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Evelin Mayanin', 'Morales Montaño', 'tup-d1805@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Yesenia', 'González Yáñez', 'tup-d1505@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Magaly Alejandra', 'Suarez Piste', 'tup-d1568@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('Tila Virginia', 'Reyes Hernandez', 'tup-d1355@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
