-- Docentes
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARTINEZ LARA', 'MARCO ANTONIO', 'tup-d116@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('TUN', 'CASTILLO LUCILA', 'tup-d1609@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('JASSO RODRIGUEZ', 'SHANTAL PATRICIA', 'tup-d1156@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GONZALEZ CARDENAS', 'JOSE GABRIEL', 'tup-d1665@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MORENO', 'ALZATE BRENDA', 'tup-d1783@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CHAVARRIA', 'MORALES ARMANDO', 'tup-d81@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ALCOCER URBIETA', 'LEYDI JACQUELIN', 'tup-d1715@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SANCHEZ ', 'RODRIGUEZ MIGUEL', 'tup-d1780@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GONZALEZ CARDENAS', 'VICTOR MANUEL', 'tup-d1034@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ORDOÑEZ', 'CRUZ LESLY', 'tup-d1695@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARTÍN PECH', 'LIZBETH JANET', 'tup-d1647@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ DOMINGUEZ', 'ALMA ISABEL', 'tup-d1432@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GUTIERREZ CORTEZ', 'JAVIER YOVANI', 'tup-d1619@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GONZALEZ MONTE', 'JOSUE TOMAS', 'tup-d1564@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ROSARIO SOSA', 'JORGE ALBERTO', 'tup-d1126@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GOMEZ LAGUNAS', 'ROCIO JANNET', 'tup-d1785@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ORTIZ ANTILLON', 'ANA NOEMI', 'tup-d1787@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CAÑIVE', 'RODRIGUEZ YAIMA', 'tup-d1666@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GARRIDO POSADAS', 'JOSE ALBERTO', 'tup-d1617@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PATIÑO SANTIAGO', 'MARIA GUADALUPE', 'tup-d1160@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ARIAS GONZALEZ', 'FRANCA ALEJANDRA', 'tup-d1784@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ARGUELLO AZPURUA', 'MARYORIE GERALDINE', 'tup-d1804@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DZUL ITZAH', 'NIDIA GUADALUPE', 'tup-d94@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CARVALLO ORTIZ', 'GEORGINA MARIA', 'tup-d1223@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('LEÓN GARCÍA', 'VICTOR GUADALUPE', 'tup-d1632@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SANCHEZ DE DIOS', 'DEMI NAOMI', 'tup-d1574@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CASANOVA GAMBOA', 'WILBERT HUMBERTO', 'tup-d1769@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PUENTES', 'AGUIRRE JESUS', 'tup-d1810@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CANELA VALLE', 'JOSE LUIS', 'tup-d1628@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MONTEMAYOR GONZÁLEZ', 'JOSÉ LUIS', 'tup-d1634@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ', 'SAAVEDRA DANIEL', 'tup-d1524@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PRADO', 'HIGAREDA ANDREA', 'tup-d1752@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARQUEZ ALAMILLA', 'DANIELA GEORGINA', 'tup-d1704@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ EDGAR', 'DANIELA AURORA', 'tup-d1753@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HEDDING RODRIGUEZ', 'ALEJANDRA BERENICE', 'tup-d1667@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('POOL ROBLES', 'JOSE GONZALO', 'tup-d1164@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('FAJARDO GONZALEZ', 'ISRAEL JESREEL', 'tup-d1700@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ PROF.-', 'JUAN FRANCISCO', 'tup-d1750@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MARFIL GOMEZ ', 'WILLY EFREN', 'tup-d1682@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SANTOS CUMI', 'FARITH AZAEL', 'tup-d1670@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ RAMIREZ', 'HECTOR LEONEL', 'tup-d1529@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('FRIAS VENTURA', 'ARMANDO JACOB', 'tup-d1697@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ZAVALA SALVADOR', 'DENNYS ELIZABETH', 'tup-d1603@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ANTONIO', 'LOPEZ NOHE', 'tup-d1419@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MAY GONGORA', 'JUAN CARLOS', 'tup-d1772@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SILVA', 'LEÓN ÁNGEL', 'tup-d1643@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PIÑA VALLE', 'ANDREA S.', 'tup-d1714@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CLEMENTE', 'MARTINEZ MARIA', 'tup-d1552@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ARANDA HANSMANN BLANCA', 'MARIA TERESA', 'tup-d1416@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PEREZ GALLEGOS', 'LUIS MIGUEL', 'tup-d1509@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MENDEZ', 'IZQUIERDO GUADALUPE', 'tup-d1809@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('VÁZQUEZ GUTIERREZ', 'LUIS ROBERTO', 'tup-d1646@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HERNANDEZ BAILON', 'JULIO CESAR', 'tup-d1709@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('ESCOTO VARELA', 'DANIEL JOSEPH', 'tup-d1621@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('FLOTA GARIBAY', 'ELBERTH ABEL', 'tup-d1412@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('IBAÑEZ PARAMO', 'CARLOS SHARICK', 'tup-d1623@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('BRAVO CASTAÑEDA', 'YESSICA LIZBETH', 'tup-d1385@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('PRECIADO HERRERA', 'LEONARDO JAVIER', 'tup-d1657@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RUIZ MARTINEZ', 'PEDRO ANTONIO', 'tup-d1614@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CATZIM PAT', 'OSCAR DAVID', 'tup-d185@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CHAVEZ  MENDOZA', 'MIGUEL ALEJANDRO', 'tup-d15@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('RIOS RODRIGUEZ', 'MARIA JOSE', 'tup-d1150@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CARDENAS HERNANDEZ', 'RUTH MONSERRAT', 'tup-d1415@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('JIMENEZ SIERRA', 'OLIVER ALAIN', 'tup-d1030@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('DE LA CRUZ', 'GOMEZ MAYIBE', 'tup-d1681@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MONTAÑO GOMEZ', 'ROSA ELVIA', 'tup-d1500@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('CHAN', 'SANCHEZ NAYELY', 'tup-d1086@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('HERNANDEZ MIRANDA GRISELL', 'DEL CARMEN', 'tup-d1656@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('MORALES MONTAÑO', 'EVELIN MAYANIN', 'tup-d1805@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('GONZÁLEZ', 'YÁÑEZ YESENIA', 'tup-d1505@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('SUAREZ PISTE', 'MAGALY ALEJANDRA', 'tup-d1568@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO docentes (nombre, apellidos, email, activo) VALUES ('REYES HERNANDEZ', 'TILA VIRGINIA', 'tup-d1355@tecplayacar.edu.mx', true) ON CONFLICT (email) DO NOTHING;
