-- Estudiantes chunk 11
INSERT INTO estudiantes (nombre, apellidos, email, matricula, activo) VALUES ('EMELY AIRAM', 'POOL CRUZ', 'tup6201@tecplayacar.edu.mx', 'TUP6201', true) ON CONFLICT (email) DO UPDATE SET nombre = EXCLUDED.nombre, apellidos = EXCLUDED.apellidos, matricula = EXCLUDED.matricula;
INSERT INTO estudiantes (nombre, apellidos, email, matricula, activo) VALUES ('WENDY RUBI', 'RAMIREZ CRUZ', 'tup6263@tecplayacar.edu.mx', 'TUP6263', true) ON CONFLICT (email) DO UPDATE SET nombre = EXCLUDED.nombre, apellidos = EXCLUDED.apellidos, matricula = EXCLUDED.matricula;
INSERT INTO estudiantes (nombre, apellidos, email, matricula, activo) VALUES ('ALONDRA GUADALUPE', 'RAMIREZ LÓPEZ', 'tup5676@tecplayacar.edu.mx', 'TUP5676', true) ON CONFLICT (email) DO UPDATE SET nombre = EXCLUDED.nombre, apellidos = EXCLUDED.apellidos, matricula = EXCLUDED.matricula;
INSERT INTO estudiantes (nombre, apellidos, email, matricula, activo) VALUES ('YANESSY BEATRIZ', 'REYES CHI', 'tup2450@tecplayacar.edu.mx', 'TUP2450', true) ON CONFLICT (email) DO UPDATE SET nombre = EXCLUDED.nombre, apellidos = EXCLUDED.apellidos, matricula = EXCLUDED.matricula;
INSERT INTO estudiantes (nombre, apellidos, email, matricula, activo) VALUES ('MONSERRAT DEL CARMEN', 'REYES GUTIERREZ', 'tup5425@tecplayacar.edu.mx', 'TUP5425', true) ON CONFLICT (email) DO UPDATE SET nombre = EXCLUDED.nombre, apellidos = EXCLUDED.apellidos, matricula = EXCLUDED.matricula;
INSERT INTO estudiantes (nombre, apellidos, email, matricula, activo) VALUES ('LESLIE SAYURI', 'SALAZAR RODRIGUEZ', 'tup5388@tecplayacar.edu.mx', 'TUP5388', true) ON CONFLICT (email) DO UPDATE SET nombre = EXCLUDED.nombre, apellidos = EXCLUDED.apellidos, matricula = EXCLUDED.matricula;
INSERT INTO estudiantes (nombre, apellidos, email, matricula, activo) VALUES ('CINDY CRISTHEL', 'TORRES OSORIO', 'tup5300@tecplayacar.edu.mx', 'TUP5300', true) ON CONFLICT (email) DO UPDATE SET nombre = EXCLUDED.nombre, apellidos = EXCLUDED.apellidos, matricula = EXCLUDED.matricula;
INSERT INTO estudiantes (nombre, apellidos, email, matricula, activo) VALUES ('ANDROSS DANIEL', 'TORRES RAMOS', 'tup3065@tecplayacar.edu.mx', 'TUP3065', true) ON CONFLICT (email) DO UPDATE SET nombre = EXCLUDED.nombre, apellidos = EXCLUDED.apellidos, matricula = EXCLUDED.matricula;
INSERT INTO estudiantes (nombre, apellidos, email, matricula, activo) VALUES ('DENNYS ADRIANA', 'TREJO MENDEZ', 'tup7064@tecplayacar.edu.mx', 'TUP7064', true) ON CONFLICT (email) DO UPDATE SET nombre = EXCLUDED.nombre, apellidos = EXCLUDED.apellidos, matricula = EXCLUDED.matricula;
INSERT INTO estudiantes (nombre, apellidos, email, matricula, activo) VALUES ('XIMENA', 'VELASCO BECERRIL', 'tup5892@tecplayacar.edu.mx', 'TUP5892', true) ON CONFLICT (email) DO UPDATE SET nombre = EXCLUDED.nombre, apellidos = EXCLUDED.apellidos, matricula = EXCLUDED.matricula;
