-- Inscripciones chunk 11
INSERT INTO inscripciones (estudiante_id, grupo_id, cuatrimestre_id) SELECT e.id, g.id, g.cuatrimestre_id FROM estudiantes e, grupos g WHERE e.email = 'tup6201@tecplayacar.edu.mx' AND g.clave = '26-3_PED_12_09B' ON CONFLICT (estudiante_id, grupo_id) DO NOTHING;
INSERT INTO inscripciones (estudiante_id, grupo_id, cuatrimestre_id) SELECT e.id, g.id, g.cuatrimestre_id FROM estudiantes e, grupos g WHERE e.email = 'tup6263@tecplayacar.edu.mx' AND g.clave = '26-3_PED_12_09B' ON CONFLICT (estudiante_id, grupo_id) DO NOTHING;
INSERT INTO inscripciones (estudiante_id, grupo_id, cuatrimestre_id) SELECT e.id, g.id, g.cuatrimestre_id FROM estudiantes e, grupos g WHERE e.email = 'tup5676@tecplayacar.edu.mx' AND g.clave = '26-3_PED_12_09B' ON CONFLICT (estudiante_id, grupo_id) DO NOTHING;
INSERT INTO inscripciones (estudiante_id, grupo_id, cuatrimestre_id) SELECT e.id, g.id, g.cuatrimestre_id FROM estudiantes e, grupos g WHERE e.email = 'tup2450@tecplayacar.edu.mx' AND g.clave = '26-3_PED_12_09B' ON CONFLICT (estudiante_id, grupo_id) DO NOTHING;
INSERT INTO inscripciones (estudiante_id, grupo_id, cuatrimestre_id) SELECT e.id, g.id, g.cuatrimestre_id FROM estudiantes e, grupos g WHERE e.email = 'tup5425@tecplayacar.edu.mx' AND g.clave = '26-3_PED_12_09B' ON CONFLICT (estudiante_id, grupo_id) DO NOTHING;
INSERT INTO inscripciones (estudiante_id, grupo_id, cuatrimestre_id) SELECT e.id, g.id, g.cuatrimestre_id FROM estudiantes e, grupos g WHERE e.email = 'tup5388@tecplayacar.edu.mx' AND g.clave = '26-3_PED_12_09B' ON CONFLICT (estudiante_id, grupo_id) DO NOTHING;
INSERT INTO inscripciones (estudiante_id, grupo_id, cuatrimestre_id) SELECT e.id, g.id, g.cuatrimestre_id FROM estudiantes e, grupos g WHERE e.email = 'tup5300@tecplayacar.edu.mx' AND g.clave = '26-3_PED_12_09B' ON CONFLICT (estudiante_id, grupo_id) DO NOTHING;
INSERT INTO inscripciones (estudiante_id, grupo_id, cuatrimestre_id) SELECT e.id, g.id, g.cuatrimestre_id FROM estudiantes e, grupos g WHERE e.email = 'tup3065@tecplayacar.edu.mx' AND g.clave = '26-3_PED_12_09B' ON CONFLICT (estudiante_id, grupo_id) DO NOTHING;
INSERT INTO inscripciones (estudiante_id, grupo_id, cuatrimestre_id) SELECT e.id, g.id, g.cuatrimestre_id FROM estudiantes e, grupos g WHERE e.email = 'tup7064@tecplayacar.edu.mx' AND g.clave = '26-3_PED_12_09B' ON CONFLICT (estudiante_id, grupo_id) DO NOTHING;
INSERT INTO inscripciones (estudiante_id, grupo_id, cuatrimestre_id) SELECT e.id, g.id, g.cuatrimestre_id FROM estudiantes e, grupos g WHERE e.email = 'tup5892@tecplayacar.edu.mx' AND g.clave = '26-3_PED_12_09B' ON CONFLICT (estudiante_id, grupo_id) DO NOTHING;
