-- Migración 024: Limpieza total de datos de prueba
TRUNCATE inscripciones RESTART IDENTITY CASCADE;
TRUNCATE encuesta_control_envio RESTART IDENTITY CASCADE;
TRUNCATE encuesta_estudiantil RESTART IDENTITY CASCADE;
TRUNCATE evaluacion_coordinacion RESTART IDENTITY CASCADE;
TRUNCATE planeaciones RESTART IDENTITY CASCADE;
TRUNCATE observaciones RESTART IDENTITY CASCADE;
TRUNCATE autodiagnosticos RESTART IDENTITY CASCADE;
TRUNCATE grupos RESTART IDENTITY CASCADE;
TRUNCATE estudiantes RESTART IDENTITY CASCADE;
TRUNCATE docentes RESTART IDENTITY CASCADE;
TRUNCATE asignaturas RESTART IDENTITY CASCADE;
-- Mantener catálogos y usuarios
