-- Depends on 040_audit_and_logical_restore_points.sql. Apply 040 first.
-- R2 object URLs are public when R2_PUBLIC_URL is configured; this table stores
-- only server-generated object paths and never accepts external image URLs.

CREATE TABLE public.institutional_notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL CHECK (length(title) BETWEEN 1 AND 160),
  body TEXT NOT NULL CHECK (length(body) BETWEEN 1 AND 4000),
  target_roles TEXT[] NOT NULL DEFAULT '{}',
  cuatrimestre_id INTEGER REFERENCES public.cuatrimestres(id),
  image_path TEXT,
  image_alt_text TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  is_active BOOLEAN NOT NULL DEFAULT true,
  published_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  created_by UUID NOT NULL REFERENCES public.usuarios(id),
  updated_by UUID NOT NULL REFERENCES public.usuarios(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (image_path IS NULL OR image_path ~ '^avisos/[0-9a-f-]{36}\.(jpg|jpeg|png|webp)$'),
  CHECK ((image_path IS NULL AND image_alt_text IS NULL) OR (image_path IS NOT NULL AND length(trim(COALESCE(image_alt_text, ''))) BETWEEN 1 AND 240)),
  CHECK (expires_at IS NULL OR published_at IS NULL OR expires_at > published_at),
  CHECK (target_roles <@ ARRAY['superadmin', 'coordinador', 'docente', 'estudiante', 'observador']::TEXT[])
);

CREATE INDEX idx_institutional_notices_feed
  ON public.institutional_notices (status, is_active, published_at DESC);
CREATE INDEX idx_institutional_notices_cycle
  ON public.institutional_notices (cuatrimestre_id, published_at DESC);

ALTER TABLE public.institutional_notices ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.institutional_notices FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.audit_institutional_notice_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_row JSONB := CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
  v_role TEXT;
BEGIN
  SELECT u.rol INTO v_role FROM public.usuarios u WHERE u.id = auth.uid();
  PERFORM public.audit_write_event(
    auth.uid(), v_role, 'database.trigger', 'institutional_notice.' || lower(TG_OP),
    NULL, 'institutional_notices', jsonb_build_object('id', v_row->>'id'), lower(TG_OP),
    '[]'::jsonb, '{}'::jsonb, '{}'::jsonb,
    jsonb_strip_nulls(jsonb_build_object(
      'status', v_row->'status',
      'is_active', v_row->'is_active',
      'cuatrimestre_id', v_row->'cuatrimestre_id',
      'has_image', v_row->>'image_path' IS NOT NULL,
      'has_expiration', v_row->'expires_at' IS NOT NULL
    ))
  );
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$function$;

CREATE TRIGGER audit_institutional_notice_change_trigger
AFTER INSERT OR UPDATE OR DELETE ON public.institutional_notices
FOR EACH ROW EXECUTE FUNCTION public.audit_institutional_notice_change();

CREATE OR REPLACE FUNCTION public.institutional_notice_admin_list()
RETURNS TABLE (
  id BIGINT, title TEXT, body TEXT, target_roles TEXT[], cuatrimestre_id INTEGER,
  image_path TEXT, image_alt_text TEXT, status TEXT, is_active BOOLEAN,
  published_at TIMESTAMPTZ, expires_at TIMESTAMPTZ, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  IF NOT public.audit_is_superadmin() THEN RAISE EXCEPTION 'superadmin required' USING ERRCODE = '42501'; END IF;
  RETURN QUERY SELECT n.id, n.title, n.body, n.target_roles, n.cuatrimestre_id,
    n.image_path, n.image_alt_text, n.status, n.is_active, n.published_at,
    n.expires_at, n.created_at, n.updated_at
  FROM public.institutional_notices n
  ORDER BY n.created_at DESC, n.id DESC
  LIMIT 200;
END;
$function$;

CREATE OR REPLACE FUNCTION public.institutional_notice_list(p_cuatrimestre_id INTEGER DEFAULT NULL)
RETURNS TABLE (
  id BIGINT, title TEXT, body TEXT, image_path TEXT, image_alt_text TEXT,
  published_at TIMESTAMPTZ, expires_at TIMESTAMPTZ
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE v_role TEXT;
BEGIN
  SELECT u.rol INTO v_role FROM public.usuarios u WHERE u.id = auth.uid() AND COALESCE(u.activo, true);
  IF v_role NOT IN ('superadmin', 'coordinador', 'docente', 'estudiante', 'observador') THEN
    RAISE EXCEPTION 'authenticated institutional role required' USING ERRCODE = '42501';
  END IF;
  IF p_cuatrimestre_id IS NOT NULL AND (p_cuatrimestre_id <= 0 OR NOT EXISTS (SELECT 1 FROM public.cuatrimestres c WHERE c.id = p_cuatrimestre_id)) THEN
    RAISE EXCEPTION 'valid cycle required' USING ERRCODE = '22023';
  END IF;
  RETURN QUERY SELECT n.id, n.title, n.body, n.image_path, n.image_alt_text, n.published_at, n.expires_at
  FROM public.institutional_notices n
  WHERE n.status = 'published'
    AND n.is_active
    AND n.published_at <= now()
    AND (n.expires_at IS NULL OR n.expires_at > now())
    AND (cardinality(n.target_roles) = 0 OR v_role = ANY(n.target_roles))
    AND (n.cuatrimestre_id IS NULL OR n.cuatrimestre_id = p_cuatrimestre_id)
  ORDER BY n.published_at DESC, n.id DESC
  LIMIT 100;
END;
$function$;

CREATE OR REPLACE FUNCTION public.institutional_notice_save(
  p_id BIGINT, p_title TEXT, p_body TEXT, p_target_roles TEXT[], p_cuatrimestre_id INTEGER,
  p_image_path TEXT, p_image_alt_text TEXT, p_status TEXT, p_is_active BOOLEAN, p_expires_at TIMESTAMPTZ
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE v_id BIGINT;
BEGIN
  IF NOT public.audit_is_superadmin() THEN RAISE EXCEPTION 'superadmin required' USING ERRCODE = '42501'; END IF;
  IF length(trim(COALESCE(p_title, ''))) NOT BETWEEN 1 AND 160 OR length(trim(COALESCE(p_body, ''))) NOT BETWEEN 1 AND 4000
    OR p_status NOT IN ('draft', 'published', 'archived') OR p_target_roles IS NULL
    OR NOT (p_target_roles <@ ARRAY['superadmin', 'coordinador', 'docente', 'estudiante', 'observador']::TEXT[])
    OR (p_image_path IS NOT NULL AND p_image_path !~ '^avisos/[0-9a-f-]{36}\.(jpg|jpeg|png|webp)$')
    OR ((p_image_path IS NULL) <> (NULLIF(trim(COALESCE(p_image_alt_text, '')), '') IS NULL)) THEN
    RAISE EXCEPTION 'invalid institutional notice input' USING ERRCODE = '22023';
  END IF;
  IF p_cuatrimestre_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.cuatrimestres c WHERE c.id = p_cuatrimestre_id) THEN
    RAISE EXCEPTION 'cycle not found' USING ERRCODE = '22023';
  END IF;
  IF p_expires_at IS NOT NULL AND p_expires_at <= now() THEN RAISE EXCEPTION 'expiration must be in the future' USING ERRCODE = '22023'; END IF;

  IF p_id IS NULL THEN
    INSERT INTO public.institutional_notices (title, body, target_roles, cuatrimestre_id, image_path, image_alt_text, status, is_active, published_at, expires_at, created_by, updated_by)
    VALUES (trim(p_title), trim(p_body), p_target_roles, p_cuatrimestre_id, p_image_path, NULLIF(trim(COALESCE(p_image_alt_text, '')), ''), p_status, p_is_active,
      CASE WHEN p_status = 'published' THEN now() END, p_expires_at, auth.uid(), auth.uid())
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.institutional_notices n
    SET title = trim(p_title), body = trim(p_body), target_roles = p_target_roles, cuatrimestre_id = p_cuatrimestre_id,
      image_path = p_image_path, image_alt_text = NULLIF(trim(COALESCE(p_image_alt_text, '')), ''), status = p_status,
      is_active = p_is_active, published_at = CASE WHEN p_status = 'published' THEN COALESCE(n.published_at, now()) ELSE n.published_at END,
      expires_at = p_expires_at, updated_by = auth.uid(), updated_at = now()
    WHERE n.id = p_id
    RETURNING n.id INTO v_id;
    IF v_id IS NULL THEN RAISE EXCEPTION 'notice not found' USING ERRCODE = '22023'; END IF;
  END IF;
  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.institutional_notice_delete(p_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  IF NOT public.audit_is_superadmin() OR p_id IS NULL OR p_id <= 0 THEN RAISE EXCEPTION 'invalid notice deletion' USING ERRCODE = '42501'; END IF;
  DELETE FROM public.institutional_notices WHERE id = p_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'notice not found' USING ERRCODE = '22023'; END IF;
END;
$function$;

REVOKE ALL ON FUNCTION public.audit_institutional_notice_change() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.institutional_notice_admin_list() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.institutional_notice_list(INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.institutional_notice_save(BIGINT, TEXT, TEXT, TEXT[], INTEGER, TEXT, TEXT, TEXT, BOOLEAN, TIMESTAMPTZ) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.institutional_notice_delete(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.institutional_notice_admin_list() TO authenticated;
GRANT EXECUTE ON FUNCTION public.institutional_notice_list(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.institutional_notice_save(BIGINT, TEXT, TEXT, TEXT[], INTEGER, TEXT, TEXT, TEXT, BOOLEAN, TIMESTAMPTZ) TO authenticated;
GRANT EXECUTE ON FUNCTION public.institutional_notice_delete(BIGINT) TO authenticated;

NOTIFY pgrst, 'reload schema';
