-- Safe, explicit hard deletion is limited to closed or inactive cycles that a
-- superadmin has deliberately marked as test data. This is not a cascade.

ALTER TABLE public.cuatrimestres
  ADD COLUMN IF NOT EXISTS es_prueba BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.test_cycle_storage_cleanup (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deleted_cycle_id INTEGER NOT NULL,
  cycle_label TEXT NOT NULL,
  bucket TEXT NOT NULL CHECK (bucket IN ('planeaciones', 'avisos')),
  object_reference TEXT NOT NULL,
  reference_kind TEXT NOT NULL CHECK (reference_kind IN ('url', 'path')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'failed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  UNIQUE (deleted_cycle_id, bucket, object_reference)
);

ALTER TABLE public.test_cycle_storage_cleanup ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.test_cycle_storage_cleanup FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.test_cycle_label(p_cycle public.cuatrimestres)
RETURNS TEXT
LANGUAGE sql
STABLE
SET search_path TO ''
AS $function$
  SELECT left(
    CASE
      WHEN NULLIF(trim(COALESCE(p_cycle.nombre, '')), '') IS NULL THEN p_cycle.clave
      ELSE p_cycle.clave || ' - ' || p_cycle.nombre
    END,
    200
  );
$function$;

-- Returns a scoped predicate only for the explicit, reviewed operational
-- tables. A new FK outside this list makes deletion fail closed below.
CREATE OR REPLACE FUNCTION public.test_cycle_scope_predicate(p_table TEXT)
RETURNS TEXT
LANGUAGE plpgsql
STABLE
SET search_path TO ''
AS $function$
DECLARE
  v_relation REGCLASS := to_regclass('public.' || p_table);
  v_has_cycle BOOLEAN;
  v_has_group BOOLEAN;
  v_has_group_fk BOOLEAN;
  v_has_run BOOLEAN;
  v_import_runs_has_cycle BOOLEAN;
  v_parts TEXT[] := ARRAY[]::TEXT[];
BEGIN
  IF v_relation IS NULL THEN RETURN NULL; END IF;
  SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_attribute a WHERE a.attrelid = v_relation AND a.attname = 'cuatrimestre_id' AND a.attnum > 0 AND NOT a.attisdropped),
         EXISTS (SELECT 1 FROM pg_catalog.pg_attribute a WHERE a.attrelid = v_relation AND a.attname = 'grupo_id' AND a.attnum > 0 AND NOT a.attisdropped),
         EXISTS (SELECT 1 FROM pg_catalog.pg_attribute a WHERE a.attrelid = v_relation AND a.attname = 'grupo_id_fk' AND a.attnum > 0 AND NOT a.attisdropped),
         EXISTS (SELECT 1 FROM pg_catalog.pg_attribute a WHERE a.attrelid = v_relation AND a.attname = 'run_id' AND a.attnum > 0 AND NOT a.attisdropped)
    INTO v_has_cycle, v_has_group, v_has_group_fk, v_has_run;

  SELECT EXISTS (
    SELECT 1 FROM pg_catalog.pg_attribute a
    WHERE a.attrelid = to_regclass('public.import_runs')
      AND a.attname = 'cuatrimestre_id' AND a.attnum > 0 AND NOT a.attisdropped
  ) INTO v_import_runs_has_cycle;
  IF p_table = 'import_issues' AND v_has_run AND v_import_runs_has_cycle THEN
    RETURN 't.run_id IN (SELECT r.id FROM public.import_runs r WHERE r.cuatrimestre_id = $1)';
  END IF;
  IF v_has_cycle THEN v_parts := array_append(v_parts, 't.cuatrimestre_id = $1'); END IF;
  IF v_has_group THEN v_parts := array_append(v_parts, 'EXISTS (SELECT 1 FROM public.grupos g WHERE g.id = t.grupo_id AND g.cuatrimestre_id = $1)'); END IF;
  IF v_has_group_fk THEN v_parts := array_append(v_parts, 'EXISTS (SELECT 1 FROM public.grupos g WHERE g.id = t.grupo_id_fk AND g.cuatrimestre_id = $1)'); END IF;
  IF cardinality(v_parts) = 0 THEN RETURN NULL; END IF;
  RETURN '(' || array_to_string(v_parts, ' OR ') || ')';
END;
$function$;

CREATE OR REPLACE FUNCTION public.test_cycle_count_rows(p_table TEXT, p_cuatrimestre_id INTEGER)
RETURNS BIGINT
LANGUAGE plpgsql
STABLE
SET search_path TO ''
AS $function$
DECLARE v_predicate TEXT; v_count BIGINT;
BEGIN
  v_predicate := public.test_cycle_scope_predicate(p_table);
  IF v_predicate IS NULL THEN RETURN 0; END IF;
  EXECUTE format('SELECT count(*) FROM public.%I t WHERE %s', p_table, v_predicate)
    INTO v_count USING p_cuatrimestre_id;
  RETURN v_count;
END;
$function$;

CREATE OR REPLACE FUNCTION public.test_cycle_delete_rows(p_table TEXT, p_cuatrimestre_id INTEGER)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE v_predicate TEXT; v_deleted BIGINT;
BEGIN
  v_predicate := public.test_cycle_scope_predicate(p_table);
  IF v_predicate IS NULL THEN RETURN 0; END IF;
  EXECUTE format('DELETE FROM public.%I t WHERE %s', p_table, v_predicate)
    USING p_cuatrimestre_id;
  GET DIAGNOSTICS v_deleted = ROW_COUNT;
  RETURN v_deleted;
END;
$function$;

-- Walk the live pg_constraint graph from cuatrimestres. This deliberately
-- rejects a schema dependency that has not been reviewed in the explicit list.
CREATE OR REPLACE FUNCTION public.test_cycle_assert_known_dependencies()
RETURNS VOID
LANGUAGE plpgsql
STABLE
SET search_path TO ''
AS $function$
DECLARE
  v_unknown TEXT;
  v_unscoped TEXT;
  v_allowed TEXT[] := ARRAY[
    'grupos', 'inscripciones', 'coordinador_docentes',
    'encuesta_control_envio', 'encuesta_estudiantil_respuestas', 'encuesta_estudiantil',
    'evaluacion_coordinacion', 'evaluacion_planeacion', 'observacion_clase',
    'autoevaluacion_docente', 'observaciones', 'planeaciones', 'autodiagnosticos',
    'docente_360_feedback', 'calificaciones_finales', 'docente_modalidad_historica',
    'notificaciones', 'institutional_notices', 'import_runs', 'import_issues'
  ];
BEGIN
  WITH RECURSIVE dependencies(relid) AS (
    SELECT 'public.cuatrimestres'::regclass::oid
    UNION
    SELECT con.conrelid
    FROM pg_catalog.pg_constraint con
    JOIN dependencies d ON d.relid = con.confrelid
    WHERE con.contype = 'f'
  ), tables AS (
    SELECT DISTINCT c.oid, c.relname
    FROM dependencies d
    JOIN pg_catalog.pg_class c ON c.oid = d.relid
    JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relname <> 'cuatrimestres'
  )
  SELECT string_agg(relname, ', ' ORDER BY relname)
    INTO v_unknown
    FROM tables
    WHERE NOT (relname = ANY(v_allowed));

  IF v_unknown IS NOT NULL THEN
    RAISE EXCEPTION 'unreviewed cycle dependency: %', v_unknown USING ERRCODE = '55000';
  END IF;

  WITH RECURSIVE dependencies(relid) AS (
    SELECT 'public.cuatrimestres'::regclass::oid
    UNION
    SELECT con.conrelid
    FROM pg_catalog.pg_constraint con
    JOIN dependencies d ON d.relid = con.confrelid
    WHERE con.contype = 'f'
  )
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
    INTO v_unscoped
    FROM dependencies d
    JOIN pg_catalog.pg_class c ON c.oid = d.relid
    JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname <> 'cuatrimestres'
      AND public.test_cycle_scope_predicate(c.relname) IS NULL;

  IF v_unscoped IS NOT NULL THEN
    RAISE EXCEPTION 'cycle dependency has no reviewed scope: %', v_unscoped USING ERRCODE = '55000';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.test_cycle_deletion_preview(p_cuatrimestre_id INTEGER)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_cycle public.cuatrimestres%ROWTYPE;
  v_table TEXT;
  v_counts JSONB := '{}'::jsonb;
  v_tables TEXT[] := ARRAY[
    'grupos', 'inscripciones', 'coordinador_docentes',
    'encuesta_control_envio', 'encuesta_estudiantil_respuestas', 'encuesta_estudiantil',
    'evaluacion_coordinacion', 'evaluacion_planeacion', 'observacion_clase',
    'autoevaluacion_docente', 'observaciones', 'planeaciones', 'autodiagnosticos',
    'docente_360_feedback', 'calificaciones_finales', 'docente_modalidad_historica',
    'notificaciones', 'institutional_notices', 'import_runs', 'import_issues'
  ];
BEGIN
  IF NOT public.audit_is_superadmin() THEN RAISE EXCEPTION 'superadmin required' USING ERRCODE = '42501'; END IF;
  IF p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 THEN RAISE EXCEPTION 'valid cycle required' USING ERRCODE = '22023'; END IF;
  SELECT * INTO v_cycle FROM public.cuatrimestres WHERE id = p_cuatrimestre_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'cycle not found' USING ERRCODE = '22023'; END IF;
  IF v_cycle.activo OR NOT v_cycle.es_prueba THEN RAISE EXCEPTION 'inactive test cycle required' USING ERRCODE = '22023'; END IF;
  PERFORM public.test_cycle_assert_known_dependencies();
  FOREACH v_table IN ARRAY v_tables LOOP
    IF to_regclass('public.' || v_table) IS NOT NULL THEN
      v_counts := v_counts || jsonb_build_object(v_table, public.test_cycle_count_rows(v_table, p_cuatrimestre_id));
    END IF;
  END LOOP;
  RETURN jsonb_build_object(
    'cycle_id', v_cycle.id,
    'cycle_label', public.test_cycle_label(v_cycle),
    'counts', v_counts,
    'audit_events_retained', true,
    'storage_cleanup_pending', (
      SELECT count(*) FROM public.test_cycle_storage_cleanup s
      WHERE s.deleted_cycle_id = p_cuatrimestre_id AND s.status = 'pending'
    )
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.mark_test_cycle(p_cuatrimestre_id INTEGER, p_confirmation TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE v_cycle public.cuatrimestres%ROWTYPE;
BEGIN
  IF NOT public.audit_is_superadmin() THEN RAISE EXCEPTION 'superadmin required' USING ERRCODE = '42501'; END IF;
  SELECT * INTO v_cycle FROM public.cuatrimestres WHERE id = p_cuatrimestre_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'cycle not found' USING ERRCODE = '22023'; END IF;
  IF v_cycle.activo THEN RAISE EXCEPTION 'active cycle cannot be marked as test' USING ERRCODE = '22023'; END IF;
  IF p_confirmation IS DISTINCT FROM public.test_cycle_label(v_cycle) THEN RAISE EXCEPTION 'cycle confirmation does not match' USING ERRCODE = '22023'; END IF;
  UPDATE public.cuatrimestres SET es_prueba = true WHERE id = v_cycle.id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.delete_test_cycle(p_cuatrimestre_id INTEGER, p_confirmation TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_cycle public.cuatrimestres%ROWTYPE;
  v_table TEXT;
  v_counts JSONB := '{}'::jsonb;
  v_role TEXT;
  v_tables TEXT[] := ARRAY[
    'import_issues', 'encuesta_estudiantil_respuestas', 'encuesta_control_envio', 'encuesta_estudiantil',
    'evaluacion_planeacion', 'observacion_clase', 'autoevaluacion_docente', 'evaluacion_coordinacion',
    'observaciones', 'planeaciones', 'autodiagnosticos', 'docente_360_feedback',
    'calificaciones_finales', 'docente_modalidad_historica', 'notificaciones',
    'institutional_notices', 'inscripciones', 'coordinador_docentes', 'import_runs', 'grupos'
  ];
BEGIN
  IF NOT public.audit_is_superadmin() THEN RAISE EXCEPTION 'superadmin required' USING ERRCODE = '42501'; END IF;
  IF p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 THEN RAISE EXCEPTION 'valid cycle required' USING ERRCODE = '22023'; END IF;
  SELECT * INTO v_cycle FROM public.cuatrimestres WHERE id = p_cuatrimestre_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'cycle not found' USING ERRCODE = '22023'; END IF;
  IF v_cycle.activo OR NOT v_cycle.es_prueba THEN RAISE EXCEPTION 'inactive test cycle required' USING ERRCODE = '22023'; END IF;
  IF p_confirmation IS DISTINCT FROM public.test_cycle_label(v_cycle) THEN RAISE EXCEPTION 'cycle confirmation does not match' USING ERRCODE = '22023'; END IF;
  PERFORM public.test_cycle_assert_known_dependencies();

  -- Persist only managed object references; the server removes them after this
  -- atomic database transaction and leaves failures visible as pending work.
  IF to_regclass('public.planeaciones') IS NOT NULL THEN
    INSERT INTO public.test_cycle_storage_cleanup (deleted_cycle_id, cycle_label, bucket, object_reference, reference_kind)
    SELECT v_cycle.id, public.test_cycle_label(v_cycle), 'planeaciones', p.url_pdf, 'url'
    FROM public.planeaciones p
    WHERE p.cuatrimestre_id = v_cycle.id AND NULLIF(trim(COALESCE(p.url_pdf, '')), '') IS NOT NULL
    ON CONFLICT (deleted_cycle_id, bucket, object_reference) DO NOTHING;
  END IF;
  IF to_regclass('public.institutional_notices') IS NOT NULL THEN
    INSERT INTO public.test_cycle_storage_cleanup (deleted_cycle_id, cycle_label, bucket, object_reference, reference_kind)
    SELECT v_cycle.id, public.test_cycle_label(v_cycle), 'avisos', n.image_path, 'path'
    FROM public.institutional_notices n
    WHERE n.cuatrimestre_id = v_cycle.id AND n.image_path IS NOT NULL
    ON CONFLICT (deleted_cycle_id, bucket, object_reference) DO NOTHING;
  END IF;

  FOREACH v_table IN ARRAY v_tables LOOP
    IF to_regclass('public.' || v_table) IS NOT NULL THEN
      v_counts := v_counts || jsonb_build_object(v_table, public.test_cycle_count_rows(v_table, v_cycle.id));
    END IF;
  END LOOP;
  SELECT u.rol INTO v_role FROM public.usuarios u WHERE u.id = auth.uid();
  PERFORM public.audit_write_event(
    auth.uid(), v_role, 'admin.test_cycle', 'test_cycle.deletion_requested', NULL,
    'cuatrimestres', jsonb_build_object('cycle_id', v_cycle.id), 'delete', '[]'::jsonb,
    '{}'::jsonb, '{}'::jsonb,
    jsonb_build_object('cycle_id', v_cycle.id, 'cycle_label', public.test_cycle_label(v_cycle),
      'operational_counts', v_counts, 'audit_events_retained', true)
  );

  FOREACH v_table IN ARRAY v_tables LOOP
    IF to_regclass('public.' || v_table) IS NOT NULL THEN
      PERFORM public.test_cycle_delete_rows(v_table, v_cycle.id);
    END IF;
  END LOOP;
  DELETE FROM public.cuatrimestres WHERE id = v_cycle.id;
  PERFORM public.refrescar_resultados_agregados();

  RETURN jsonb_build_object(
    'cycle_id', v_cycle.id,
    'cycle_label', public.test_cycle_label(v_cycle),
    'counts', v_counts,
    'audit_events_retained', true,
    'storage_cleanup_pending', (
      SELECT count(*) FROM public.test_cycle_storage_cleanup s
      WHERE s.deleted_cycle_id = v_cycle.id AND s.status = 'pending'
    )
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.test_cycle_storage_cleanup_pending(p_deleted_cycle_id INTEGER)
RETURNS TABLE(id BIGINT, bucket TEXT, object_reference TEXT, reference_kind TEXT)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  IF NOT public.audit_is_superadmin() OR p_deleted_cycle_id IS NULL OR p_deleted_cycle_id <= 0 THEN
    RAISE EXCEPTION 'superadmin and valid deleted cycle required' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY SELECT s.id, s.bucket, s.object_reference, s.reference_kind
  FROM public.test_cycle_storage_cleanup s
  WHERE s.deleted_cycle_id = p_deleted_cycle_id AND s.status IN ('pending', 'failed')
  ORDER BY s.id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.complete_test_cycle_storage_cleanup(p_id BIGINT, p_success BOOLEAN)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  IF NOT public.audit_is_superadmin() OR p_id IS NULL OR p_id <= 0 THEN RAISE EXCEPTION 'superadmin required' USING ERRCODE = '42501'; END IF;
  UPDATE public.test_cycle_storage_cleanup
  SET status = CASE WHEN p_success THEN 'completed' ELSE 'failed' END,
      completed_at = CASE WHEN p_success THEN now() ELSE NULL END
  WHERE id = p_id AND status IN ('pending', 'failed');
END;
$function$;

REVOKE ALL ON FUNCTION public.test_cycle_label(public.cuatrimestres) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.test_cycle_scope_predicate(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.test_cycle_count_rows(TEXT, INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.test_cycle_delete_rows(TEXT, INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.test_cycle_assert_known_dependencies() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.test_cycle_deletion_preview(INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.mark_test_cycle(INTEGER, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.delete_test_cycle(INTEGER, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.test_cycle_storage_cleanup_pending(INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.complete_test_cycle_storage_cleanup(BIGINT, BOOLEAN) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.test_cycle_deletion_preview(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_test_cycle(INTEGER, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_test_cycle(INTEGER, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.test_cycle_storage_cleanup_pending(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_test_cycle_storage_cleanup(BIGINT, BOOLEAN) TO authenticated;

NOTIFY pgrst, 'reload schema';
