-- Coordinator visibility and observation authority are separate relationships.
-- The legacy coordinador_docentes table remains historical compatibility data only.

CREATE TABLE public.coordinated_teacher_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coordinador_id UUID NOT NULL REFERENCES public.usuarios(id),
  docente_id INTEGER NOT NULL REFERENCES public.docentes(id),
  cuatrimestre_id INTEGER NOT NULL REFERENCES public.cuatrimestres(id),
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  assigned_by UUID REFERENCES public.usuarios(id),
  revoked_at TIMESTAMPTZ,
  revoked_by UUID REFERENCES public.usuarios(id),
  source TEXT NOT NULL DEFAULT 'admin' CHECK (source IN ('admin', 'legacy_backfill')),
  CHECK ((revoked_at IS NULL) = (revoked_by IS NULL))
);

CREATE TABLE public.observation_teacher_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evaluator_id UUID NOT NULL REFERENCES public.usuarios(id),
  docente_id INTEGER NOT NULL REFERENCES public.docentes(id),
  cuatrimestre_id INTEGER NOT NULL REFERENCES public.cuatrimestres(id),
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  assigned_by UUID REFERENCES public.usuarios(id),
  revoked_at TIMESTAMPTZ,
  revoked_by UUID REFERENCES public.usuarios(id),
  source TEXT NOT NULL DEFAULT 'admin' CHECK (source IN ('admin', 'legacy_backfill')),
  CHECK ((revoked_at IS NULL) = (revoked_by IS NULL))
);

-- This records whether every legacy relation was migrated or requires review,
-- without copying names, emails, comments, or other free text into audit data.
CREATE TABLE public.teacher_assignment_backfill_review (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_actor_id UUID NOT NULL REFERENCES public.usuarios(id),
  docente_id INTEGER NOT NULL REFERENCES public.docentes(id),
  cuatrimestre_id INTEGER NOT NULL REFERENCES public.cuatrimestres(id),
  target_assignment_type TEXT CHECK (target_assignment_type IN ('coordinated', 'observation')),
  status TEXT NOT NULL CHECK (status IN ('backfilled', 'needs_review')),
  reason_code TEXT NOT NULL CHECK (reason_code IN ('coordinator', 'observer', 'inactive_actor', 'inactive_teacher', 'unsupported_role')),
  reviewed_at TIMESTAMPTZ,
  reviewed_by UUID REFERENCES public.usuarios(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (legacy_actor_id, docente_id, cuatrimestre_id)
);

CREATE UNIQUE INDEX coordinated_teacher_assignments_active_unique
  ON public.coordinated_teacher_assignments (coordinador_id, docente_id, cuatrimestre_id)
  WHERE revoked_at IS NULL;
CREATE UNIQUE INDEX observation_teacher_assignments_active_unique
  ON public.observation_teacher_assignments (evaluator_id, docente_id, cuatrimestre_id)
  WHERE revoked_at IS NULL;
CREATE INDEX coordinated_teacher_assignments_cycle_teacher_idx
  ON public.coordinated_teacher_assignments (cuatrimestre_id, docente_id) WHERE revoked_at IS NULL;
CREATE INDEX observation_teacher_assignments_cycle_teacher_idx
  ON public.observation_teacher_assignments (cuatrimestre_id, docente_id) WHERE revoked_at IS NULL;
CREATE INDEX teacher_assignment_backfill_review_cycle_idx
  ON public.teacher_assignment_backfill_review (cuatrimestre_id, status);

ALTER TABLE public.coordinated_teacher_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.observation_teacher_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_assignment_backfill_review ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.coordinated_teacher_assignments, public.observation_teacher_assignments,
  public.teacher_assignment_backfill_review FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.validate_teacher_assignment_actor()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_actor_id UUID;
  v_role TEXT;
  v_active BOOLEAN;
BEGIN
  v_actor_id := CASE WHEN TG_TABLE_NAME = 'coordinated_teacher_assignments' THEN NEW.coordinador_id ELSE NEW.evaluator_id END;
  SELECT u.rol, COALESCE(u.activo, true) INTO v_role, v_active FROM public.usuarios u WHERE u.id = v_actor_id;
  IF NOT FOUND OR NOT v_active
    OR (TG_TABLE_NAME = 'coordinated_teacher_assignments' AND v_role <> 'coordinador')
    OR (TG_TABLE_NAME = 'observation_teacher_assignments' AND v_role NOT IN ('coordinador', 'observador')) THEN
    RAISE EXCEPTION 'active actor with an allowed role required' USING ERRCODE = '42501';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.docentes d WHERE d.id = NEW.docente_id) THEN
    RAISE EXCEPTION 'teacher required' USING ERRCODE = '42501';
  END IF;
  IF TG_OP = 'UPDATE' AND (
    NEW.docente_id IS DISTINCT FROM OLD.docente_id OR NEW.cuatrimestre_id IS DISTINCT FROM OLD.cuatrimestre_id
    OR v_actor_id IS DISTINCT FROM CASE WHEN TG_TABLE_NAME = 'coordinated_teacher_assignments' THEN OLD.coordinador_id ELSE OLD.evaluator_id END
    OR NEW.assigned_at IS DISTINCT FROM OLD.assigned_at OR NEW.assigned_by IS DISTINCT FROM OLD.assigned_by
    OR NEW.source IS DISTINCT FROM OLD.source
  ) THEN
    RAISE EXCEPTION 'assignment identity is immutable' USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END;
$function$;

CREATE TRIGGER validate_coordinated_teacher_assignment_actor
BEFORE INSERT OR UPDATE ON public.coordinated_teacher_assignments
FOR EACH ROW EXECUTE FUNCTION public.validate_teacher_assignment_actor();
CREATE TRIGGER validate_observation_teacher_assignment_actor
BEFORE INSERT OR UPDATE ON public.observation_teacher_assignments
FOR EACH ROW EXECUTE FUNCTION public.validate_teacher_assignment_actor();

-- A coordinated relationship grants the 360, planning, reporting, notification,
-- and individual-teacher scope. Observation is intentionally not implied.
CREATE OR REPLACE FUNCTION public.can_manage_coordinated_teacher(
  p_docente_id INTEGER, p_cuatrimestre_id INTEGER, p_actor_id UUID DEFAULT auth.uid()
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
  SELECT p_docente_id > 0 AND p_cuatrimestre_id > 0 AND (
    EXISTS (SELECT 1 FROM public.usuarios u WHERE u.id = p_actor_id AND u.rol = 'superadmin' AND COALESCE(u.activo, true))
    OR EXISTS (
      SELECT 1 FROM public.coordinated_teacher_assignments a
      JOIN public.usuarios u ON u.id = a.coordinador_id
      WHERE a.coordinador_id = p_actor_id AND a.docente_id = p_docente_id AND a.cuatrimestre_id = p_cuatrimestre_id
        AND a.revoked_at IS NULL AND u.rol = 'coordinador' AND COALESCE(u.activo, true)
    )
  );
$function$;

CREATE OR REPLACE FUNCTION public.can_observe_assigned_teacher(
  p_docente_id INTEGER, p_cuatrimestre_id INTEGER, p_actor_id UUID DEFAULT auth.uid()
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
  SELECT p_docente_id > 0 AND p_cuatrimestre_id > 0 AND (
    EXISTS (SELECT 1 FROM public.usuarios u WHERE u.id = p_actor_id AND u.rol = 'superadmin' AND COALESCE(u.activo, true))
    OR EXISTS (
      SELECT 1 FROM public.observation_teacher_assignments a
      JOIN public.usuarios u ON u.id = a.evaluator_id
      WHERE a.evaluator_id = p_actor_id AND a.docente_id = p_docente_id AND a.cuatrimestre_id = p_cuatrimestre_id
        AND a.revoked_at IS NULL AND u.rol IN ('coordinador', 'observador') AND COALESCE(u.activo, true)
    )
  );
$function$;

CREATE OR REPLACE FUNCTION public.my_coordinated_teacher_ids(p_cuatrimestre_id INTEGER)
RETURNS TABLE(docente_id INTEGER)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE v_role TEXT;
BEGIN
  SELECT u.rol INTO v_role FROM public.usuarios u WHERE u.id = auth.uid() AND COALESCE(u.activo, true);
  IF v_role = 'superadmin' THEN
    RETURN QUERY SELECT d.id FROM public.docentes d WHERE COALESCE(d.activo, true);
  ELSIF v_role = 'coordinador' THEN
    RETURN QUERY SELECT a.docente_id FROM public.coordinated_teacher_assignments a
      WHERE a.coordinador_id = auth.uid() AND a.cuatrimestre_id = p_cuatrimestre_id AND a.revoked_at IS NULL;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.my_observation_teacher_ids(p_cuatrimestre_id INTEGER)
RETURNS TABLE(docente_id INTEGER)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE v_role TEXT;
BEGIN
  SELECT u.rol INTO v_role FROM public.usuarios u WHERE u.id = auth.uid() AND COALESCE(u.activo, true);
  IF v_role = 'superadmin' THEN
    RETURN QUERY SELECT d.id FROM public.docentes d WHERE COALESCE(d.activo, true);
  ELSIF v_role IN ('coordinador', 'observador') THEN
    RETURN QUERY SELECT a.docente_id FROM public.observation_teacher_assignments a
      WHERE a.evaluator_id = auth.uid() AND a.cuatrimestre_id = p_cuatrimestre_id AND a.revoked_at IS NULL;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_teacher_assignment_list(p_cuatrimestre_id INTEGER)
RETURNS TABLE(assignment_type TEXT, actor_id UUID, actor_email TEXT, actor_role TEXT, docente_id INTEGER, source TEXT, assigned_at TIMESTAMPTZ)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  IF NOT public.audit_is_superadmin() OR p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 THEN
    RAISE EXCEPTION 'superadmin and valid cycle required' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY
    SELECT 'coordinated'::TEXT, a.coordinador_id, u.email, u.rol, a.docente_id, a.source, a.assigned_at
    FROM public.coordinated_teacher_assignments a JOIN public.usuarios u ON u.id = a.coordinador_id
    WHERE a.cuatrimestre_id = p_cuatrimestre_id AND a.revoked_at IS NULL
    UNION ALL
    SELECT 'observation'::TEXT, a.evaluator_id, u.email, u.rol, a.docente_id, a.source, a.assigned_at
    FROM public.observation_teacher_assignments a JOIN public.usuarios u ON u.id = a.evaluator_id
    WHERE a.cuatrimestre_id = p_cuatrimestre_id AND a.revoked_at IS NULL;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_teacher_assignment_backfill_status(p_cuatrimestre_id INTEGER)
RETURNS TABLE(assignment_type TEXT, status TEXT, reason_code TEXT, assignment_count BIGINT)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  IF NOT public.audit_is_superadmin() OR p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 THEN
    RAISE EXCEPTION 'superadmin and valid cycle required' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY SELECT COALESCE(r.target_assignment_type, 'review'), r.status, r.reason_code, count(*)
    FROM public.teacher_assignment_backfill_review r WHERE r.cuatrimestre_id = p_cuatrimestre_id
    GROUP BY r.target_assignment_type, r.status, r.reason_code;
END;
$function$;

CREATE OR REPLACE FUNCTION public.replace_teacher_assignments(
  p_assignment_type TEXT, p_actor_id UUID, p_cuatrimestre_id INTEGER, p_docente_ids INTEGER[]
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE v_role TEXT; v_ids INTEGER[]; v_added INTEGER; v_revoked INTEGER;
BEGIN
  -- A PostgREST RPC invocation runs this replace, its revocations, and its audit
  -- event in one database transaction; any validation failure rolls all back.
  IF NOT public.audit_is_superadmin() OR p_assignment_type NOT IN ('coordinated', 'observation')
    OR p_actor_id IS NULL OR p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 OR p_docente_ids IS NULL
    OR NOT EXISTS (SELECT 1 FROM public.cuatrimestres c WHERE c.id = p_cuatrimestre_id) THEN
    RAISE EXCEPTION 'invalid teacher assignment request' USING ERRCODE = '22023';
  END IF;
  SELECT u.rol INTO v_role FROM public.usuarios u WHERE u.id = p_actor_id AND COALESCE(u.activo, true);
  IF NOT FOUND OR (p_assignment_type = 'coordinated' AND v_role <> 'coordinador')
    OR (p_assignment_type = 'observation' AND v_role NOT IN ('coordinador', 'observador')) THEN
    RAISE EXCEPTION 'actor role is not eligible for assignment type' USING ERRCODE = '42501';
  END IF;
  SELECT COALESCE(array_agg(DISTINCT x), ARRAY[]::INTEGER[]) INTO v_ids FROM unnest(p_docente_ids) AS x WHERE x > 0;
  IF cardinality(v_ids) <> cardinality(p_docente_ids) OR EXISTS (
    SELECT 1 FROM unnest(v_ids) x WHERE NOT EXISTS (SELECT 1 FROM public.docentes d WHERE d.id = x)
  ) THEN RAISE EXCEPTION 'unique teacher ids required' USING ERRCODE = '22023'; END IF;

  IF p_assignment_type = 'coordinated' THEN
    UPDATE public.coordinated_teacher_assignments SET revoked_at = now(), revoked_by = auth.uid()
      WHERE coordinador_id = p_actor_id AND cuatrimestre_id = p_cuatrimestre_id AND revoked_at IS NULL AND NOT (docente_id = ANY(v_ids));
    GET DIAGNOSTICS v_revoked = ROW_COUNT;
    UPDATE public.coordinated_teacher_assignments SET revoked_at = NULL, revoked_by = NULL
      WHERE coordinador_id = p_actor_id AND cuatrimestre_id = p_cuatrimestre_id AND revoked_at IS NOT NULL AND docente_id = ANY(v_ids);
    INSERT INTO public.coordinated_teacher_assignments (coordinador_id, docente_id, cuatrimestre_id, assigned_by)
      SELECT p_actor_id, x, p_cuatrimestre_id, auth.uid() FROM unnest(v_ids) x
      WHERE NOT EXISTS (SELECT 1 FROM public.coordinated_teacher_assignments a WHERE a.coordinador_id = p_actor_id AND a.docente_id = x AND a.cuatrimestre_id = p_cuatrimestre_id);
    GET DIAGNOSTICS v_added = ROW_COUNT;
  ELSE
    UPDATE public.observation_teacher_assignments SET revoked_at = now(), revoked_by = auth.uid()
      WHERE evaluator_id = p_actor_id AND cuatrimestre_id = p_cuatrimestre_id AND revoked_at IS NULL AND NOT (docente_id = ANY(v_ids));
    GET DIAGNOSTICS v_revoked = ROW_COUNT;
    UPDATE public.observation_teacher_assignments SET revoked_at = NULL, revoked_by = NULL
      WHERE evaluator_id = p_actor_id AND cuatrimestre_id = p_cuatrimestre_id AND revoked_at IS NOT NULL AND docente_id = ANY(v_ids);
    INSERT INTO public.observation_teacher_assignments (evaluator_id, docente_id, cuatrimestre_id, assigned_by)
      SELECT p_actor_id, x, p_cuatrimestre_id, auth.uid() FROM unnest(v_ids) x
      WHERE NOT EXISTS (SELECT 1 FROM public.observation_teacher_assignments a WHERE a.evaluator_id = p_actor_id AND a.docente_id = x AND a.cuatrimestre_id = p_cuatrimestre_id);
    GET DIAGNOSTICS v_added = ROW_COUNT;
  END IF;
  PERFORM public.audit_write_event(auth.uid(), 'superadmin', 'admin.assignment', 'teacher_assignment.replaced', NULL,
    'teacher_assignments', jsonb_build_object('actor_id', p_actor_id, 'cuatrimestre_id', p_cuatrimestre_id, 'assignment_type', p_assignment_type),
    'replace', '[]'::jsonb, '{}'::jsonb, '{}'::jsonb,
    jsonb_build_object('assignment_type', p_assignment_type, 'cuatrimestre_id', p_cuatrimestre_id, 'requested_count', cardinality(v_ids), 'inserted_count', v_added, 'revoked_count', v_revoked));
  RETURN cardinality(v_ids);
END;
$function$;

-- Backfill only active, role-eligible actors. A coordinator gets
-- coordination scope only; it never receives observation scope from legacy data.
INSERT INTO public.teacher_assignment_backfill_review (
  legacy_actor_id, docente_id, cuatrimestre_id, target_assignment_type, status, reason_code
)
SELECT cd.coordinador_id, cd.docente_id, cd.cuatrimestre_id,
  CASE WHEN u.rol = 'coordinador' THEN 'coordinated' WHEN u.rol = 'observador' THEN 'observation' END,
  CASE WHEN u.rol IN ('coordinador', 'observador') AND COALESCE(u.activo, true) THEN 'backfilled' ELSE 'needs_review' END,
  CASE WHEN u.rol = 'coordinador' THEN 'coordinator' WHEN u.rol = 'observador' THEN 'observer'
    WHEN NOT COALESCE(u.activo, true) THEN 'inactive_actor' ELSE 'unsupported_role' END
FROM public.coordinador_docentes cd
JOIN public.usuarios u ON u.id = cd.coordinador_id
JOIN public.docentes d ON d.id = cd.docente_id
WHERE cd.cuatrimestre_id IS NOT NULL
ON CONFLICT (legacy_actor_id, docente_id, cuatrimestre_id) DO NOTHING;

INSERT INTO public.coordinated_teacher_assignments (coordinador_id, docente_id, cuatrimestre_id, source)
SELECT r.legacy_actor_id, r.docente_id, r.cuatrimestre_id, 'legacy_backfill'
FROM public.teacher_assignment_backfill_review r
WHERE r.target_assignment_type = 'coordinated' AND r.status = 'backfilled'
ON CONFLICT (coordinador_id, docente_id, cuatrimestre_id) WHERE revoked_at IS NULL DO NOTHING;

INSERT INTO public.observation_teacher_assignments (evaluator_id, docente_id, cuatrimestre_id, source)
SELECT r.legacy_actor_id, r.docente_id, r.cuatrimestre_id, 'legacy_backfill'
FROM public.teacher_assignment_backfill_review r
WHERE r.target_assignment_type = 'observation' AND r.status = 'backfilled'
ON CONFLICT (evaluator_id, docente_id, cuatrimestre_id) WHERE revoked_at IS NULL DO NOTHING;

CREATE OR REPLACE FUNCTION public.enforce_staff_assignment_authorization()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE v_role TEXT; v_docente_id INTEGER; v_cycle_id INTEGER;
BEGIN
  SELECT u.rol INTO v_role FROM public.usuarios u WHERE u.id = auth.uid() AND COALESCE(u.activo, true);
  IF v_role IS NULL OR v_role = 'superadmin' THEN RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END; END IF;
  v_docente_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.docente_id ELSE NEW.docente_id END;
  v_cycle_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.cuatrimestre_id ELSE NEW.cuatrimestre_id END;
  IF TG_TABLE_NAME = 'observaciones' AND NOT public.can_observe_assigned_teacher(v_docente_id, v_cycle_id) THEN
    RAISE EXCEPTION 'observation assignment required' USING ERRCODE = '42501';
  END IF;
  IF TG_TABLE_NAME = 'evaluacion_coordinacion' AND NOT public.can_manage_coordinated_teacher(v_docente_id, v_cycle_id) THEN
    RAISE EXCEPTION 'coordinated teacher assignment required' USING ERRCODE = '42501';
  END IF;
  IF TG_TABLE_NAME = 'planeaciones' AND v_role = 'coordinador'
    AND TG_OP = 'UPDATE' AND NEW.fecha_evaluacion IS DISTINCT FROM OLD.fecha_evaluacion
    AND NOT public.can_manage_coordinated_teacher(v_docente_id, v_cycle_id) THEN
    RAISE EXCEPTION 'coordinated teacher assignment required' USING ERRCODE = '42501';
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$function$;

DROP TRIGGER IF EXISTS enforce_observation_assignment_authorization ON public.observaciones;
CREATE TRIGGER enforce_observation_assignment_authorization
BEFORE INSERT OR UPDATE OR DELETE ON public.observaciones
FOR EACH ROW EXECUTE FUNCTION public.enforce_staff_assignment_authorization();
DROP TRIGGER IF EXISTS enforce_coordination_assignment_authorization ON public.evaluacion_coordinacion;
CREATE TRIGGER enforce_coordination_assignment_authorization
BEFORE INSERT OR UPDATE OR DELETE ON public.evaluacion_coordinacion
FOR EACH ROW EXECUTE FUNCTION public.enforce_staff_assignment_authorization();
DROP TRIGGER IF EXISTS enforce_planning_assignment_authorization ON public.planeaciones;
CREATE TRIGGER enforce_planning_assignment_authorization
BEFORE UPDATE ON public.planeaciones
FOR EACH ROW EXECUTE FUNCTION public.enforce_staff_assignment_authorization();

-- Student-score aggregation is performance data, so observers never receive it
-- through the legacy aggregate RPC. Coordinators require their coordinated scope.
CREATE OR REPLACE FUNCTION public.obtener_scores_encuesta_estudiantil_nativa(p_cuatrimestre_id INTEGER)
RETURNS TABLE(cuatrimestre_id INTEGER, docente_id INTEGER, asignatura_id INTEGER, grupo_id INTEGER, respuestas_validas BIGINT, score_normalizado NUMERIC, version_calculo TEXT)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO '' AS $function$
DECLARE v_rol VARCHAR(20); v_docente_id INT;
BEGIN
  IF p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 OR NOT EXISTS (SELECT 1 FROM public.cuatrimestres c WHERE c.id = p_cuatrimestre_id) THEN RAISE EXCEPTION 'valid cycle id required' USING ERRCODE = '22023'; END IF;
  IF auth.role() IS DISTINCT FROM 'service_role' THEN
    SELECT u.rol, u.entidad_id INTO v_rol, v_docente_id FROM public.usuarios u WHERE u.id = auth.uid() AND COALESCE(u.activo, true);
    IF v_rol IS NULL OR v_rol NOT IN ('superadmin', 'coordinador', 'docente') THEN RAISE EXCEPTION 'authorized role required' USING ERRCODE = '42501'; END IF;
  END IF;
  RETURN QUERY
  WITH valid_responses AS (
    SELECT g.cuatrimestre_id, g.docente_id, g.asignatura_id, g.id AS grupo_id,
      ((r.calidad_general + r.item_plan_estudio + r.item_trato_respeto + r.item_asistencia + r.item_puntualidad + r.item_participacion + r.item_dominio_materia + r.item_plataforma_moodle + r.item_pensamiento_critico + r.item_desafio_intelectual + r.item_claridad_objetivos + r.item_lecturas_aprendizaje + r.item_respeto_reglas + r.item_interes_materia + r.item_apoyos_didacticos + r.item_actitudes_valores + r.item_retroalimentacion + r.item_criterios_evaluacion + r.item_receptividad - 19)::NUMERIC / (19 * 4) * 100) AS response_score
    FROM public.encuesta_estudiantil_respuestas r JOIN public.grupos g ON g.id = r.grupo_id AND g.cuatrimestre_id = p_cuatrimestre_id AND g.docente_id = r.docente_id
    WHERE r.cuatrimestre_id = p_cuatrimestre_id
      AND r.calidad_general BETWEEN 1 AND 5 AND r.item_plan_estudio BETWEEN 1 AND 5 AND r.item_trato_respeto BETWEEN 1 AND 5 AND r.item_asistencia BETWEEN 1 AND 5 AND r.item_puntualidad BETWEEN 1 AND 5 AND r.item_participacion BETWEEN 1 AND 5 AND r.item_dominio_materia BETWEEN 1 AND 5 AND r.item_plataforma_moodle BETWEEN 1 AND 5 AND r.item_pensamiento_critico BETWEEN 1 AND 5 AND r.item_desafio_intelectual BETWEEN 1 AND 5 AND r.item_claridad_objetivos BETWEEN 1 AND 5 AND r.item_lecturas_aprendizaje BETWEEN 1 AND 5 AND r.item_respeto_reglas BETWEEN 1 AND 5 AND r.item_interes_materia BETWEEN 1 AND 5 AND r.item_apoyos_didacticos BETWEEN 1 AND 5 AND r.item_actitudes_valores BETWEEN 1 AND 5 AND r.item_retroalimentacion BETWEEN 1 AND 5 AND r.item_criterios_evaluacion BETWEEN 1 AND 5 AND r.item_receptividad BETWEEN 1 AND 5
      AND (auth.role() = 'service_role' OR v_rol = 'superadmin' OR (v_rol = 'coordinador' AND public.can_manage_coordinated_teacher(g.docente_id, p_cuatrimestre_id)) OR (v_rol = 'docente' AND g.docente_id = v_docente_id))
  ) SELECT r.cuatrimestre_id, r.docente_id, r.asignatura_id, r.grupo_id, COUNT(*)::BIGINT, AVG(r.response_score), 'native-19-v2'::TEXT FROM valid_responses r GROUP BY r.cuatrimestre_id, r.docente_id, r.asignatura_id, r.grupo_id ORDER BY r.docente_id, r.asignatura_id, r.grupo_id;
END;
$function$;

-- Extend test-cycle FK closure, preview, and deletion in the same forward migration.
CREATE OR REPLACE FUNCTION public.test_cycle_assert_known_dependencies()
RETURNS VOID LANGUAGE plpgsql STABLE SET search_path TO '' AS $function$
DECLARE v_unknown TEXT; v_unscoped TEXT;
  v_allowed TEXT[] := ARRAY['autodiagnosticos','autoevaluacion_docente','calificacion_final_docente','calificaciones_finales','coordinador_docentes','coordinated_teacher_assignments','observation_teacher_assignments','teacher_assignment_backfill_review','docente_360_feedback','docente_modalidad_historica','encuesta_control_envio','encuesta_estudiantil','encuesta_estudiantil_respuestas','evaluacion_coordinacion','evaluacion_planeacion','grupos','import_issues','import_runs','inscripciones','institutional_notices','observacion_clase','observaciones','planeaciones','planning_submission_windows'];
BEGIN
  WITH RECURSIVE dependencies(relid) AS (SELECT 'public.cuatrimestres'::regclass::oid UNION SELECT con.conrelid FROM pg_catalog.pg_constraint con JOIN dependencies d ON d.relid = con.confrelid WHERE con.contype = 'f'), tables AS (SELECT DISTINCT c.oid, c.relname FROM dependencies d JOIN pg_catalog.pg_class c ON c.oid = d.relid JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname <> 'cuatrimestres') SELECT string_agg(relname, ', ' ORDER BY relname) INTO v_unknown FROM tables WHERE NOT (relname = ANY(v_allowed));
  IF v_unknown IS NOT NULL THEN RAISE EXCEPTION 'test cycle dependency guard blocked deletion' USING ERRCODE = 'TC004'; END IF;
  WITH RECURSIVE dependencies(relid) AS (SELECT 'public.cuatrimestres'::regclass::oid UNION SELECT con.conrelid FROM pg_catalog.pg_constraint con JOIN dependencies d ON d.relid = con.confrelid WHERE con.contype = 'f') SELECT string_agg(c.relname, ', ' ORDER BY c.relname) INTO v_unscoped FROM dependencies d JOIN pg_catalog.pg_class c ON c.oid = d.relid JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname <> 'cuatrimestres' AND public.test_cycle_scope_predicate(c.relname) IS NULL;
  IF v_unscoped IS NOT NULL THEN RAISE EXCEPTION 'test cycle dependency guard blocked deletion' USING ERRCODE = 'TC004'; END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.test_cycle_deletion_preview(p_cuatrimestre_id INTEGER)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO '' AS $function$
DECLARE v_cycle public.cuatrimestres%ROWTYPE; v_table TEXT; v_counts JSONB := '{}'::jsonb;
  v_tables TEXT[] := ARRAY['autodiagnosticos','autoevaluacion_docente','calificacion_final_docente','calificaciones_finales','coordinador_docentes','coordinated_teacher_assignments','observation_teacher_assignments','teacher_assignment_backfill_review','docente_360_feedback','docente_modalidad_historica','encuesta_control_envio','encuesta_estudiantil','encuesta_estudiantil_respuestas','evaluacion_coordinacion','evaluacion_planeacion','grupos','import_issues','import_runs','inscripciones','institutional_notices','observacion_clase','observaciones','planeaciones','planning_submission_windows'];
BEGIN
  IF NOT public.audit_is_superadmin() THEN RAISE EXCEPTION 'superadmin required' USING ERRCODE = '42501'; END IF;
  IF p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 THEN RAISE EXCEPTION 'valid cycle required' USING ERRCODE = '22023'; END IF;
  SELECT * INTO v_cycle FROM public.cuatrimestres WHERE id = p_cuatrimestre_id; IF NOT FOUND THEN RAISE EXCEPTION 'test cycle not found' USING ERRCODE = 'TC005'; END IF;
  PERFORM public.test_cycle_assert_deletable(v_cycle); PERFORM public.test_cycle_assert_known_dependencies();
  FOREACH v_table IN ARRAY v_tables LOOP IF to_regclass('public.' || v_table) IS NOT NULL THEN v_counts := v_counts || jsonb_build_object(v_table, public.test_cycle_count_rows(v_table, p_cuatrimestre_id)); END IF; END LOOP;
  RETURN jsonb_build_object('cycle_id', v_cycle.id, 'cycle_label', public.test_cycle_label(v_cycle), 'counts', v_counts, 'audit_events_retained', true, 'storage_cleanup_pending', (SELECT count(*) FROM public.test_cycle_storage_cleanup s WHERE s.deleted_cycle_id = p_cuatrimestre_id AND s.status = 'pending'));
END;
$function$;

CREATE OR REPLACE FUNCTION public.delete_test_cycle(p_cuatrimestre_id INTEGER, p_confirmation TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $function$
DECLARE v_cycle public.cuatrimestres%ROWTYPE; v_table TEXT; v_counts JSONB := '{}'::jsonb; v_role TEXT; v_audit_suppression_token UUID;
  v_tables TEXT[] := ARRAY['autodiagnosticos','autoevaluacion_docente','calificacion_final_docente','calificaciones_finales','coordinador_docentes','coordinated_teacher_assignments','observation_teacher_assignments','teacher_assignment_backfill_review','docente_360_feedback','docente_modalidad_historica','encuesta_control_envio','encuesta_estudiantil','encuesta_estudiantil_respuestas','evaluacion_coordinacion','evaluacion_planeacion','grupos','import_issues','import_runs','inscripciones','institutional_notices','observacion_clase','observaciones','planeaciones','planning_submission_windows'];
BEGIN
  IF NOT public.audit_is_superadmin() THEN RAISE EXCEPTION 'superadmin required' USING ERRCODE = '42501'; END IF;
  IF p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 THEN RAISE EXCEPTION 'valid cycle required' USING ERRCODE = '22023'; END IF;
  SELECT * INTO v_cycle FROM public.cuatrimestres WHERE id = p_cuatrimestre_id FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'test cycle not found' USING ERRCODE = 'TC005'; END IF;
  PERFORM public.test_cycle_assert_deletable(v_cycle, p_confirmation); PERFORM public.test_cycle_assert_known_dependencies();
  IF to_regclass('public.planeaciones') IS NOT NULL THEN INSERT INTO public.test_cycle_storage_cleanup (deleted_cycle_id, cycle_label, bucket, object_reference, reference_kind) SELECT v_cycle.id, public.test_cycle_label(v_cycle), 'planeaciones', p.url_pdf, 'url' FROM public.planeaciones p WHERE p.cuatrimestre_id = v_cycle.id AND NULLIF(trim(COALESCE(p.url_pdf, '')), '') IS NOT NULL ON CONFLICT (deleted_cycle_id, bucket, object_reference) DO NOTHING; END IF;
  IF to_regclass('public.institutional_notices') IS NOT NULL THEN INSERT INTO public.test_cycle_storage_cleanup (deleted_cycle_id, cycle_label, bucket, object_reference, reference_kind) SELECT v_cycle.id, public.test_cycle_label(v_cycle), 'avisos', n.image_path, 'path' FROM public.institutional_notices n WHERE n.cuatrimestre_id = v_cycle.id AND n.image_path IS NOT NULL ON CONFLICT (deleted_cycle_id, bucket, object_reference) DO NOTHING; END IF;
  FOREACH v_table IN ARRAY v_tables LOOP IF to_regclass('public.' || v_table) IS NOT NULL THEN v_counts := v_counts || jsonb_build_object(v_table, public.test_cycle_count_rows(v_table, v_cycle.id)); END IF; END LOOP;
  SELECT u.rol INTO v_role FROM public.usuarios u WHERE u.id = auth.uid(); PERFORM public.audit_write_event(auth.uid(), v_role, 'admin.test_cycle', 'test_cycle.deleted', NULL, 'cuatrimestres', jsonb_build_object('cycle_id', v_cycle.id), 'delete', '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, jsonb_build_object('cycle_id', v_cycle.id, 'cycle_label', public.test_cycle_label(v_cycle), 'operational_counts', v_counts, 'audit_events_retained', true));
  v_audit_suppression_token := extensions.gen_random_uuid(); PERFORM set_config('app.private_test_cycle_delete_audit_token', v_audit_suppression_token::TEXT, true); INSERT INTO public.test_cycle_audit_suppression_context (transaction_id, backend_pid, actor_id, token) VALUES (txid_current(), pg_backend_pid(), auth.uid(), v_audit_suppression_token);
  PERFORM public.test_cycle_delete_rows('import_issues', v_cycle.id); PERFORM public.test_cycle_delete_rows('encuesta_estudiantil_respuestas', v_cycle.id); PERFORM public.test_cycle_delete_rows('encuesta_control_envio', v_cycle.id); IF to_regclass('public.encuesta_estudiantil') IS NOT NULL THEN PERFORM public.test_cycle_delete_rows('encuesta_estudiantil', v_cycle.id); END IF;
  PERFORM public.test_cycle_delete_rows('evaluacion_planeacion', v_cycle.id); PERFORM public.test_cycle_delete_rows('observacion_clase', v_cycle.id); PERFORM public.test_cycle_delete_rows('autoevaluacion_docente', v_cycle.id); PERFORM public.test_cycle_delete_rows('evaluacion_coordinacion', v_cycle.id); PERFORM public.test_cycle_delete_rows('observaciones', v_cycle.id); PERFORM public.test_cycle_delete_rows('planeaciones', v_cycle.id); PERFORM public.test_cycle_delete_rows('planning_submission_windows', v_cycle.id); PERFORM public.test_cycle_delete_rows('autodiagnosticos', v_cycle.id); PERFORM public.test_cycle_delete_rows('docente_360_feedback', v_cycle.id); IF to_regclass('public.calificacion_final_docente') IS NOT NULL THEN PERFORM public.test_cycle_delete_rows('calificacion_final_docente', v_cycle.id); END IF; PERFORM public.test_cycle_delete_rows('calificaciones_finales', v_cycle.id); IF to_regclass('public.docente_modalidad_historica') IS NOT NULL THEN PERFORM public.test_cycle_delete_rows('docente_modalidad_historica', v_cycle.id); END IF; PERFORM public.test_cycle_delete_rows('institutional_notices', v_cycle.id); PERFORM public.test_cycle_delete_rows('inscripciones', v_cycle.id); PERFORM public.test_cycle_delete_rows('teacher_assignment_backfill_review', v_cycle.id); PERFORM public.test_cycle_delete_rows('coordinated_teacher_assignments', v_cycle.id); PERFORM public.test_cycle_delete_rows('observation_teacher_assignments', v_cycle.id); PERFORM public.test_cycle_delete_rows('coordinador_docentes', v_cycle.id); PERFORM public.test_cycle_delete_rows('import_runs', v_cycle.id); PERFORM public.test_cycle_delete_rows('grupos', v_cycle.id);
  DELETE FROM public.cuatrimestres WHERE id = v_cycle.id; DELETE FROM public.test_cycle_audit_suppression_context WHERE transaction_id = txid_current() AND backend_pid = pg_backend_pid() AND actor_id = auth.uid() AND token = v_audit_suppression_token; PERFORM set_config('app.private_test_cycle_delete_audit_token', '', true); PERFORM public.refrescar_resultados_agregados();
  RETURN jsonb_build_object('cycle_id', v_cycle.id, 'cycle_label', public.test_cycle_label(v_cycle), 'counts', v_counts, 'audit_events_retained', true, 'storage_cleanup_pending', (SELECT count(*) FROM public.test_cycle_storage_cleanup s WHERE s.deleted_cycle_id = v_cycle.id AND s.status = 'pending'));
END;
$function$;

REVOKE ALL ON FUNCTION public.validate_teacher_assignment_actor() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.can_manage_coordinated_teacher(INTEGER, INTEGER, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.can_observe_assigned_teacher(INTEGER, INTEGER, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.my_coordinated_teacher_ids(INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.my_observation_teacher_ids(INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_teacher_assignment_list(INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_teacher_assignment_backfill_status(INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.replace_teacher_assignments(TEXT, UUID, INTEGER, INTEGER[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.enforce_staff_assignment_authorization() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.test_cycle_assert_known_dependencies() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.test_cycle_deletion_preview(INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.delete_test_cycle(INTEGER, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.can_manage_coordinated_teacher(INTEGER, INTEGER, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_observe_assigned_teacher(INTEGER, INTEGER, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_coordinated_teacher_ids(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_observation_teacher_ids(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_teacher_assignment_list(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_teacher_assignment_backfill_status(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.replace_teacher_assignments(TEXT, UUID, INTEGER, INTEGER[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.test_cycle_deletion_preview(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_test_cycle(INTEGER, TEXT) TO authenticated;

NOTIFY pgrst, 'reload schema';
