-- Administrative assignment management follows the purpose split in 051.
-- Later proposed instrument migrations must start at 053; this migration is
-- intentionally independent of instrument-format and N/A scoring changes.

ALTER TABLE public.observation_teacher_assignments
  DROP CONSTRAINT observation_teacher_assignments_source_check;
ALTER TABLE public.observation_teacher_assignments
  ADD CONSTRAINT observation_teacher_assignments_source_check
  CHECK (source IN ('admin', 'legacy_backfill', 'automatic_allocation'));

CREATE TABLE public.observation_allocation_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cuatrimestre_id INTEGER NOT NULL REFERENCES public.cuatrimestres(id),
  evaluator_id UUID NOT NULL REFERENCES public.usuarios(id),
  included BOOLEAN NOT NULL DEFAULT true,
  target_teacher_count INTEGER CHECK (target_teacher_count IS NULL OR target_teacher_count BETWEEN 0 AND 10000),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by UUID NOT NULL REFERENCES public.usuarios(id),
  UNIQUE (cuatrimestre_id, evaluator_id)
);

CREATE TABLE public.observation_allocation_previews (
  id UUID PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
  cuatrimestre_id INTEGER NOT NULL REFERENCES public.cuatrimestres(id),
  seed UUID NOT NULL,
  fingerprint UUID NOT NULL DEFAULT extensions.gen_random_uuid(),
  created_by UUID NOT NULL REFERENCES public.usuarios(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,
  proposal JSONB NOT NULL,
  summary JSONB NOT NULL,
  confirmed_at TIMESTAMPTZ,
  confirmed_by UUID REFERENCES public.usuarios(id),
  CHECK (expires_at > created_at),
  CHECK ((confirmed_at IS NULL) = (confirmed_by IS NULL))
);

CREATE TABLE public.observation_allocation_runs (
  id UUID PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
  preview_id UUID NOT NULL UNIQUE REFERENCES public.observation_allocation_previews(id),
  cuatrimestre_id INTEGER NOT NULL REFERENCES public.cuatrimestres(id),
  seed UUID NOT NULL,
  initiated_by UUID NOT NULL REFERENCES public.usuarios(id),
  initiated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  counts JSONB NOT NULL
);

CREATE INDEX observation_allocation_preferences_cycle_idx
  ON public.observation_allocation_preferences (cuatrimestre_id, included);
CREATE INDEX observation_allocation_previews_cycle_created_idx
  ON public.observation_allocation_previews (cuatrimestre_id, created_at DESC);
CREATE INDEX observation_allocation_runs_cycle_initiated_idx
  ON public.observation_allocation_runs (cuatrimestre_id, initiated_at DESC);

ALTER TABLE public.observation_allocation_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.observation_allocation_previews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.observation_allocation_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.observation_allocation_preferences, public.observation_allocation_previews,
  public.observation_allocation_runs FROM PUBLIC, anon, authenticated;

-- Observation may be assigned to an active administrator, coordinator, or
-- observer. Coordination remains coordinator-only.
CREATE OR REPLACE FUNCTION public.validate_teacher_assignment_actor()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_actor_id UUID;
  v_role TEXT;
  v_active BOOLEAN;
BEGIN
  v_actor_id := CASE WHEN TG_TABLE_NAME = 'coordinated_teacher_assignments' THEN NEW.coordinador_id ELSE NEW.evaluator_id END;
  SELECT u.rol, COALESCE(u.activo, true) INTO v_role, v_active FROM public.usuarios u WHERE u.id = v_actor_id;
  IF NOT FOUND OR NOT v_active
    OR (TG_TABLE_NAME = 'coordinated_teacher_assignments' AND v_role <> 'coordinador')
    OR (TG_TABLE_NAME = 'observation_teacher_assignments' AND v_role NOT IN ('superadmin', 'coordinador', 'observador')) THEN
    RAISE EXCEPTION 'active actor with an allowed role required' USING ERRCODE = '42501';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.docentes d WHERE d.id = NEW.docente_id) THEN
    RAISE EXCEPTION 'teacher required' USING ERRCODE = '42501';
  END IF;
  IF TG_OP = 'UPDATE' AND (
    NEW.docente_id IS DISTINCT FROM OLD.docente_id OR NEW.cuatrimestre_id IS DISTINCT FROM OLD.cuatrimestre_id
    OR v_actor_id IS DISTINCT FROM CASE WHEN TG_TABLE_NAME = 'coordinated_teacher_assignments' THEN OLD.coordinador_id ELSE OLD.evaluator_id END
    OR NEW.assigned_at IS DISTINCT FROM OLD.assigned_at OR NEW.assigned_by IS DISTINCT FROM OLD.assigned_by
    OR NEW.source IS DISTINCT FROM OLD.source
  ) THEN
    RAISE EXCEPTION 'assignment identity is immutable' USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.validate_observation_allocation_preference()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  IF NEW.target_teacher_count IS NOT NULL AND NEW.target_teacher_count NOT BETWEEN 0 AND 10000 THEN
    RAISE EXCEPTION 'target must be between zero and 10000' USING ERRCODE = '22023';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.usuarios u
    WHERE u.id = NEW.evaluator_id AND COALESCE(u.activo, true)
      AND u.rol IN ('superadmin', 'coordinador', 'observador')
  ) THEN
    RAISE EXCEPTION 'active observation evaluator required' USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END;
$function$;

CREATE TRIGGER validate_observation_allocation_preference
BEFORE INSERT OR UPDATE ON public.observation_allocation_preferences
FOR EACH ROW EXECUTE FUNCTION public.validate_observation_allocation_preference();

CREATE OR REPLACE FUNCTION public.admin_assignment_teacher_candidates(
  p_cuatrimestre_id INTEGER, p_search TEXT DEFAULT '', p_include_all_active BOOLEAN DEFAULT false
)
RETURNS TABLE(docente_id INTEGER, nombre TEXT, apellidos TEXT, academic_activity BOOLEAN)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE v_search TEXT := left(trim(COALESCE(p_search, '')), 120);
BEGIN
  IF NOT public.audit_is_superadmin() OR p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0
    OR NOT EXISTS (SELECT 1 FROM public.cuatrimestres c WHERE c.id = p_cuatrimestre_id) THEN
    RAISE EXCEPTION 'superadmin and valid cycle required' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY
  SELECT d.id, d.nombre, d.apellidos,
    EXISTS (SELECT 1 FROM public.grupos g WHERE g.docente_id = d.id AND g.cuatrimestre_id = p_cuatrimestre_id AND g.activo IS TRUE)
  FROM public.docentes d
  WHERE d.activo IS TRUE
    AND (p_include_all_active OR EXISTS (
      SELECT 1 FROM public.grupos g WHERE g.docente_id = d.id AND g.cuatrimestre_id = p_cuatrimestre_id AND g.activo IS TRUE
    ))
    AND (v_search = '' OR concat_ws(' ', d.nombre, d.apellidos) ILIKE '%' || v_search || '%')
  ORDER BY d.apellidos, d.nombre, d.id
  LIMIT 500;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_teacher_assignment_list_v2(p_cuatrimestre_id INTEGER)
RETURNS TABLE(assignment_id BIGINT, assignment_type TEXT, actor_id UUID, docente_id INTEGER, source TEXT, assigned_at TIMESTAMPTZ)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  IF NOT public.audit_is_superadmin() OR p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 THEN
    RAISE EXCEPTION 'superadmin and valid cycle required' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY
    SELECT a.id, 'coordinated'::TEXT, a.coordinador_id, a.docente_id, a.source, a.assigned_at
    FROM public.coordinated_teacher_assignments a
    WHERE a.cuatrimestre_id = p_cuatrimestre_id AND a.revoked_at IS NULL
    UNION ALL
    SELECT a.id, 'observation'::TEXT, a.evaluator_id, a.docente_id, a.source, a.assigned_at
    FROM public.observation_teacher_assignments a
    WHERE a.cuatrimestre_id = p_cuatrimestre_id AND a.revoked_at IS NULL;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_observation_allocation_evaluators(p_cuatrimestre_id INTEGER)
RETURNS TABLE(evaluator_id UUID, email TEXT, role TEXT, included BOOLEAN, target_teacher_count INTEGER, current_count BIGINT)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  IF NOT public.audit_is_superadmin() OR p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0
    OR NOT EXISTS (SELECT 1 FROM public.cuatrimestres c WHERE c.id = p_cuatrimestre_id) THEN
    RAISE EXCEPTION 'superadmin and valid cycle required' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY
  SELECT u.id, u.email, u.rol, COALESCE(p.included, true), p.target_teacher_count,
    count(a.id)::BIGINT
  FROM public.usuarios u
  LEFT JOIN public.observation_allocation_preferences p
    ON p.evaluator_id = u.id AND p.cuatrimestre_id = p_cuatrimestre_id
  LEFT JOIN public.observation_teacher_assignments a
    ON a.evaluator_id = u.id AND a.cuatrimestre_id = p_cuatrimestre_id AND a.revoked_at IS NULL
  WHERE COALESCE(u.activo, true) AND u.rol IN ('superadmin', 'coordinador', 'observador')
  GROUP BY u.id, u.email, u.rol, p.included, p.target_teacher_count
  ORDER BY CASE u.rol WHEN 'superadmin' THEN 0 WHEN 'coordinador' THEN 1 ELSE 2 END, u.email;
END;
$function$;

CREATE OR REPLACE FUNCTION public.assign_teacher_assignments(
  p_assignment_type TEXT, p_actor_id UUID, p_cuatrimestre_id INTEGER, p_docente_ids INTEGER[]
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE v_role TEXT; v_ids INTEGER[]; v_added INTEGER := 0; v_restored INTEGER := 0;
BEGIN
  IF NOT public.audit_is_superadmin() OR p_assignment_type NOT IN ('coordinated', 'observation')
    OR p_actor_id IS NULL OR p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 OR p_docente_ids IS NULL
    OR cardinality(p_docente_ids) > 500
    OR NOT EXISTS (SELECT 1 FROM public.cuatrimestres c WHERE c.id = p_cuatrimestre_id) THEN
    RAISE EXCEPTION 'invalid teacher assignment request' USING ERRCODE = '22023';
  END IF;
  PERFORM 1 FROM public.cuatrimestres c WHERE c.id = p_cuatrimestre_id FOR UPDATE;
  SELECT u.rol INTO v_role FROM public.usuarios u WHERE u.id = p_actor_id AND COALESCE(u.activo, true);
  IF NOT FOUND OR (p_assignment_type = 'coordinated' AND v_role <> 'coordinador')
    OR (p_assignment_type = 'observation' AND v_role NOT IN ('superadmin', 'coordinador', 'observador')) THEN
    RAISE EXCEPTION 'actor role is not eligible for assignment type' USING ERRCODE = '42501';
  END IF;
  SELECT COALESCE(array_agg(DISTINCT x), ARRAY[]::INTEGER[]) INTO v_ids FROM unnest(p_docente_ids) AS x WHERE x > 0;
  IF cardinality(v_ids) <> cardinality(p_docente_ids) OR EXISTS (
    SELECT 1 FROM unnest(v_ids) x WHERE NOT EXISTS (SELECT 1 FROM public.docentes d WHERE d.id = x)
  ) THEN RAISE EXCEPTION 'unique teacher ids required' USING ERRCODE = '22023'; END IF;

  IF p_assignment_type = 'coordinated' THEN
    UPDATE public.coordinated_teacher_assignments SET revoked_at = NULL, revoked_by = NULL
      WHERE coordinador_id = p_actor_id AND cuatrimestre_id = p_cuatrimestre_id AND revoked_at IS NOT NULL AND docente_id = ANY(v_ids);
    GET DIAGNOSTICS v_restored = ROW_COUNT;
    INSERT INTO public.coordinated_teacher_assignments (coordinador_id, docente_id, cuatrimestre_id, assigned_by)
      SELECT p_actor_id, x, p_cuatrimestre_id, auth.uid() FROM unnest(v_ids) x
      WHERE NOT EXISTS (SELECT 1 FROM public.coordinated_teacher_assignments a WHERE a.coordinador_id = p_actor_id AND a.docente_id = x AND a.cuatrimestre_id = p_cuatrimestre_id)
      ON CONFLICT (coordinador_id, docente_id, cuatrimestre_id) WHERE revoked_at IS NULL DO NOTHING;
  ELSE
    UPDATE public.observation_teacher_assignments SET revoked_at = NULL, revoked_by = NULL
      WHERE evaluator_id = p_actor_id AND cuatrimestre_id = p_cuatrimestre_id AND revoked_at IS NOT NULL AND docente_id = ANY(v_ids);
    GET DIAGNOSTICS v_restored = ROW_COUNT;
    INSERT INTO public.observation_teacher_assignments (evaluator_id, docente_id, cuatrimestre_id, assigned_by)
      SELECT p_actor_id, x, p_cuatrimestre_id, auth.uid() FROM unnest(v_ids) x
      WHERE NOT EXISTS (SELECT 1 FROM public.observation_teacher_assignments a WHERE a.evaluator_id = p_actor_id AND a.docente_id = x AND a.cuatrimestre_id = p_cuatrimestre_id)
      ON CONFLICT (evaluator_id, docente_id, cuatrimestre_id) WHERE revoked_at IS NULL DO NOTHING;
  END IF;
  GET DIAGNOSTICS v_added = ROW_COUNT;
  PERFORM public.audit_write_event(auth.uid(), 'superadmin', 'admin.assignment', 'teacher_assignment.assigned', NULL,
    'teacher_assignments', jsonb_build_object('cuatrimestre_id', p_cuatrimestre_id, 'assignment_type', p_assignment_type),
    'insert', '[]'::jsonb, '{}'::jsonb, '{}'::jsonb,
    jsonb_build_object('assignment_type', p_assignment_type, 'cuatrimestre_id', p_cuatrimestre_id, 'requested_count', cardinality(v_ids), 'inserted_count', v_added, 'restored_count', v_restored));
  RETURN v_added + v_restored;
END;
$function$;

CREATE OR REPLACE FUNCTION public.revoke_teacher_assignments(
  p_assignment_type TEXT, p_cuatrimestre_id INTEGER, p_assignment_ids BIGINT[]
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE v_ids BIGINT[]; v_revoked INTEGER := 0;
BEGIN
  IF NOT public.audit_is_superadmin() OR p_assignment_type NOT IN ('coordinated', 'observation')
    OR p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 OR p_assignment_ids IS NULL OR cardinality(p_assignment_ids) > 500 THEN
    RAISE EXCEPTION 'invalid assignment revocation request' USING ERRCODE = '22023';
  END IF;
  SELECT COALESCE(array_agg(DISTINCT x), ARRAY[]::BIGINT[]) INTO v_ids FROM unnest(p_assignment_ids) AS x WHERE x > 0;
  IF cardinality(v_ids) <> cardinality(p_assignment_ids) THEN RAISE EXCEPTION 'unique assignment ids required' USING ERRCODE = '22023'; END IF;
  PERFORM 1 FROM public.cuatrimestres c WHERE c.id = p_cuatrimestre_id FOR UPDATE;
  IF p_assignment_type = 'coordinated' THEN
    UPDATE public.coordinated_teacher_assignments SET revoked_at = now(), revoked_by = auth.uid()
      WHERE id = ANY(v_ids) AND cuatrimestre_id = p_cuatrimestre_id AND revoked_at IS NULL;
  ELSE
    UPDATE public.observation_teacher_assignments SET revoked_at = now(), revoked_by = auth.uid()
      WHERE id = ANY(v_ids) AND cuatrimestre_id = p_cuatrimestre_id AND revoked_at IS NULL;
  END IF;
  GET DIAGNOSTICS v_revoked = ROW_COUNT;
  PERFORM public.audit_write_event(auth.uid(), 'superadmin', 'admin.assignment', 'teacher_assignment.revoked', NULL,
    'teacher_assignments', jsonb_build_object('cuatrimestre_id', p_cuatrimestre_id, 'assignment_type', p_assignment_type),
    'update', '[]'::jsonb, '{}'::jsonb, '{}'::jsonb,
    jsonb_build_object('assignment_type', p_assignment_type, 'cuatrimestre_id', p_cuatrimestre_id, 'requested_count', cardinality(v_ids), 'revoked_count', v_revoked));
  RETURN v_revoked;
END;
$function$;

CREATE OR REPLACE FUNCTION public.save_observation_allocation_preferences(
  p_cuatrimestre_id INTEGER, p_preferences JSONB
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE v_item JSONB; v_evaluator_id UUID; v_included BOOLEAN; v_target INTEGER; v_seen UUID[] := ARRAY[]::UUID[]; v_saved INTEGER := 0;
BEGIN
  IF NOT public.audit_is_superadmin() OR p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0
    OR jsonb_typeof(p_preferences) <> 'array' OR jsonb_array_length(p_preferences) > 250
    OR NOT EXISTS (SELECT 1 FROM public.cuatrimestres c WHERE c.id = p_cuatrimestre_id) THEN
    RAISE EXCEPTION 'invalid allocation preferences' USING ERRCODE = '22023';
  END IF;
  PERFORM 1 FROM public.cuatrimestres c WHERE c.id = p_cuatrimestre_id FOR UPDATE;
  FOR v_item IN SELECT value FROM jsonb_array_elements(p_preferences) LOOP
    IF jsonb_typeof(v_item) <> 'object' OR COALESCE(v_item->>'evaluator_id', '') !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
      OR jsonb_typeof(v_item->'included') <> 'boolean'
      OR (v_item ? 'target_teacher_count' AND v_item->'target_teacher_count' <> 'null'::jsonb AND jsonb_typeof(v_item->'target_teacher_count') <> 'number') THEN
      RAISE EXCEPTION 'invalid allocation preference item' USING ERRCODE = '22023';
    END IF;
    v_evaluator_id := (v_item->>'evaluator_id')::UUID;
    v_included := (v_item->>'included')::BOOLEAN;
    v_target := CASE WHEN v_item->'target_teacher_count' IS NULL OR v_item->'target_teacher_count' = 'null'::jsonb THEN NULL ELSE (v_item->>'target_teacher_count')::INTEGER END;
    IF v_target IS NOT NULL AND v_target NOT BETWEEN 0 AND 10000 OR v_evaluator_id = ANY(v_seen) THEN
      RAISE EXCEPTION 'invalid allocation preference item' USING ERRCODE = '22023';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.usuarios u WHERE u.id = v_evaluator_id AND COALESCE(u.activo, true) AND u.rol IN ('superadmin', 'coordinador', 'observador')) THEN
      RAISE EXCEPTION 'active observation evaluator required' USING ERRCODE = '42501';
    END IF;
    INSERT INTO public.observation_allocation_preferences (cuatrimestre_id, evaluator_id, included, target_teacher_count, updated_at, updated_by)
      VALUES (p_cuatrimestre_id, v_evaluator_id, v_included, v_target, now(), auth.uid())
      ON CONFLICT (cuatrimestre_id, evaluator_id) DO UPDATE SET included = EXCLUDED.included,
        target_teacher_count = EXCLUDED.target_teacher_count, updated_at = EXCLUDED.updated_at, updated_by = EXCLUDED.updated_by;
    v_seen := array_append(v_seen, v_evaluator_id); v_saved := v_saved + 1;
  END LOOP;
  PERFORM public.audit_write_event(auth.uid(), 'superadmin', 'admin.observation_allocation', 'observation_allocation.preferences_saved', NULL,
    'observation_allocation_preferences', jsonb_build_object('cuatrimestre_id', p_cuatrimestre_id), 'upsert',
    '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, jsonb_build_object('cuatrimestre_id', p_cuatrimestre_id, 'evaluator_count', v_saved));
  RETURN v_saved;
END;
$function$;

CREATE OR REPLACE FUNCTION public.preview_observation_allocation(p_cuatrimestre_id INTEGER)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_seed UUID := extensions.gen_random_uuid(); v_fingerprint UUID := extensions.gen_random_uuid(); v_preview_id UUID;
  v_plan JSONB := '{}'::jsonb; v_summary JSONB; v_candidates INTEGER[] := ARRAY[]::INTEGER[];
  v_targeted UUID[] := ARRAY[]::UUID[]; v_untargeted UUID[] := ARRAY[]::UUID[];
  v_evaluator RECORD; v_evaluator_id UUID; v_current INTEGER; v_target INTEGER; v_needed INTEGER;
  v_cursor INTEGER := 0; v_i INTEGER; v_best_id UUID; v_best_load INTEGER; v_load INTEGER; v_best_tie TEXT; v_tie TEXT;
BEGIN
  IF NOT public.audit_is_superadmin() OR p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0
    OR NOT EXISTS (SELECT 1 FROM public.cuatrimestres c WHERE c.id = p_cuatrimestre_id) THEN
    RAISE EXCEPTION 'superadmin and valid cycle required' USING ERRCODE = '42501';
  END IF;
  FOR v_evaluator IN
    SELECT u.id, COALESCE(p.included, true) AS included, p.target_teacher_count,
      count(a.id)::INTEGER AS current_count
    FROM public.usuarios u
    LEFT JOIN public.observation_allocation_preferences p ON p.evaluator_id = u.id AND p.cuatrimestre_id = p_cuatrimestre_id
    LEFT JOIN public.observation_teacher_assignments a ON a.evaluator_id = u.id AND a.cuatrimestre_id = p_cuatrimestre_id AND a.revoked_at IS NULL
    WHERE COALESCE(u.activo, true) AND u.rol IN ('superadmin', 'coordinador', 'observador')
    GROUP BY u.id, p.included, p.target_teacher_count
    ORDER BY md5(v_seed::TEXT || ':' || u.id::TEXT)
  LOOP
    v_plan := v_plan || jsonb_build_object(v_evaluator.id::TEXT, jsonb_build_object(
      'included', v_evaluator.included, 'target', v_evaluator.target_teacher_count,
      'current', v_evaluator.current_count, 'proposed_teacher_ids', '[]'::jsonb
    ));
    IF v_evaluator.included THEN
      IF v_evaluator.target_teacher_count IS NULL THEN v_untargeted := array_append(v_untargeted, v_evaluator.id);
      ELSE v_targeted := array_append(v_targeted, v_evaluator.id); END IF;
    END IF;
  END LOOP;
  SELECT COALESCE(array_agg(candidate.docente_id), ARRAY[]::INTEGER[]) INTO v_candidates FROM (
    SELECT d.id AS docente_id
    FROM public.docentes d
    WHERE d.activo IS TRUE
      AND EXISTS (SELECT 1 FROM public.grupos g WHERE g.docente_id = d.id AND g.cuatrimestre_id = p_cuatrimestre_id AND g.activo IS TRUE)
      AND NOT EXISTS (SELECT 1 FROM public.observation_teacher_assignments a WHERE a.docente_id = d.id AND a.cuatrimestre_id = p_cuatrimestre_id AND a.revoked_at IS NULL)
    ORDER BY md5(v_seed::TEXT || ':' || d.id::TEXT)
  ) candidate;

  FOREACH v_evaluator_id IN ARRAY v_targeted LOOP
    v_current := (v_plan -> v_evaluator_id::TEXT ->> 'current')::INTEGER;
    v_target := (v_plan -> v_evaluator_id::TEXT ->> 'target')::INTEGER;
    v_needed := greatest(v_target - v_current, 0);
    IF v_needed > 0 THEN
      FOR v_i IN 1..least(v_needed, cardinality(v_candidates) - v_cursor) LOOP
        v_cursor := v_cursor + 1;
        v_plan := jsonb_set(v_plan, ARRAY[v_evaluator_id::TEXT, 'proposed_teacher_ids'],
          (v_plan -> v_evaluator_id::TEXT -> 'proposed_teacher_ids') || jsonb_build_array(v_candidates[v_cursor]), true);
      END LOOP;
    END IF;
  END LOOP;
  WHILE v_cursor < cardinality(v_candidates) AND cardinality(v_untargeted) > 0 LOOP
    v_best_id := NULL; v_best_load := NULL; v_best_tie := NULL;
    FOREACH v_evaluator_id IN ARRAY v_untargeted LOOP
      v_load := (v_plan -> v_evaluator_id::TEXT ->> 'current')::INTEGER + jsonb_array_length(v_plan -> v_evaluator_id::TEXT -> 'proposed_teacher_ids');
      v_tie := md5(v_seed::TEXT || ':' || v_candidates[v_cursor + 1]::TEXT || ':' || v_evaluator_id::TEXT);
      IF v_best_id IS NULL OR v_load < v_best_load OR (v_load = v_best_load AND v_tie < v_best_tie) THEN
        v_best_id := v_evaluator_id; v_best_load := v_load; v_best_tie := v_tie;
      END IF;
    END LOOP;
    v_cursor := v_cursor + 1;
    v_plan := jsonb_set(v_plan, ARRAY[v_best_id::TEXT, 'proposed_teacher_ids'],
      (v_plan -> v_best_id::TEXT -> 'proposed_teacher_ids') || jsonb_build_array(v_candidates[v_cursor]), true);
  END LOOP;
  SELECT COALESCE(jsonb_object_agg(key, jsonb_build_object(
    'included', value -> 'included', 'current', (value ->> 'current')::INTEGER, 'target', value -> 'target',
    'proposed', jsonb_array_length(value -> 'proposed_teacher_ids'),
    'final', (value ->> 'current')::INTEGER + jsonb_array_length(value -> 'proposed_teacher_ids'),
    'exceeds_target', value -> 'target' <> 'null'::jsonb AND (value ->> 'current')::INTEGER > (value ->> 'target')::INTEGER,
    'target_shortfall', value -> 'target' <> 'null'::jsonb AND (value ->> 'current')::INTEGER + jsonb_array_length(value -> 'proposed_teacher_ids') < (value ->> 'target')::INTEGER
  )), '{}'::jsonb) INTO v_summary FROM jsonb_each(v_plan);
  INSERT INTO public.observation_allocation_previews (cuatrimestre_id, seed, fingerprint, created_by, expires_at, proposal, summary)
    VALUES (p_cuatrimestre_id, v_seed, v_fingerprint, auth.uid(), now() + interval '15 minutes', v_plan, v_summary)
    RETURNING id INTO v_preview_id;
  PERFORM public.audit_write_event(auth.uid(), 'superadmin', 'admin.observation_allocation', 'observation_allocation.previewed', NULL,
    'observation_allocation_previews', jsonb_build_object('cuatrimestre_id', p_cuatrimestre_id), 'insert',
    '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, jsonb_build_object('cuatrimestre_id', p_cuatrimestre_id, 'candidate_count', cardinality(v_candidates), 'proposed_count', v_cursor, 'included_evaluator_count', cardinality(v_targeted) + cardinality(v_untargeted)));
  RETURN jsonb_build_object('preview_id', v_preview_id, 'fingerprint', v_fingerprint, 'seed', v_seed,
    'candidate_count', cardinality(v_candidates), 'evaluator_counts', v_summary);
END;
$function$;

CREATE OR REPLACE FUNCTION public.confirm_observation_allocation(p_cuatrimestre_id INTEGER, p_preview_id UUID, p_fingerprint UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_preview public.observation_allocation_previews%ROWTYPE; v_run public.observation_allocation_runs%ROWTYPE;
  v_item RECORD; v_evaluator_id UUID; v_included BOOLEAN; v_target INTEGER; v_current INTEGER; v_expected_current INTEGER;
  v_planned INTEGER := 0; v_inserted INTEGER := 0; v_row_count INTEGER; v_teacher_id INTEGER;
BEGIN
  IF NOT public.audit_is_superadmin() OR p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 OR p_preview_id IS NULL OR p_fingerprint IS NULL THEN
    RAISE EXCEPTION 'superadmin and preview required' USING ERRCODE = '42501';
  END IF;
  SELECT * INTO v_preview FROM public.observation_allocation_previews
    WHERE id = p_preview_id AND cuatrimestre_id = p_cuatrimestre_id AND fingerprint = p_fingerprint AND created_by = auth.uid() FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'allocation preview not found' USING ERRCODE = '22023'; END IF;
  IF v_preview.confirmed_at IS NOT NULL THEN
    SELECT * INTO v_run FROM public.observation_allocation_runs WHERE preview_id = v_preview.id;
    RETURN jsonb_build_object('run_id', v_run.id, 'already_confirmed', true, 'assigned_count', COALESCE((v_run.counts ->> 'assigned_count')::INTEGER, 0), 'evaluator_counts', v_preview.summary);
  END IF;
  IF v_preview.expires_at <= now() THEN RAISE EXCEPTION 'allocation preview expired' USING ERRCODE = '22023'; END IF;
  PERFORM 1 FROM public.cuatrimestres c WHERE c.id = v_preview.cuatrimestre_id FOR UPDATE;
  FOR v_item IN SELECT key, value FROM jsonb_each(v_preview.proposal) LOOP
    v_evaluator_id := v_item.key::UUID;
    v_included := (v_item.value ->> 'included')::BOOLEAN;
    v_target := CASE WHEN v_item.value -> 'target' = 'null'::jsonb THEN NULL ELSE (v_item.value ->> 'target')::INTEGER END;
    v_expected_current := (v_item.value ->> 'current')::INTEGER;
    SELECT count(*)::INTEGER INTO v_current FROM public.observation_teacher_assignments a
      WHERE a.evaluator_id = v_evaluator_id AND a.cuatrimestre_id = v_preview.cuatrimestre_id AND a.revoked_at IS NULL;
    IF v_current <> v_expected_current OR NOT EXISTS (
      SELECT 1 FROM public.usuarios u LEFT JOIN public.observation_allocation_preferences p
        ON p.evaluator_id = u.id AND p.cuatrimestre_id = v_preview.cuatrimestre_id
      WHERE u.id = v_evaluator_id AND COALESCE(u.activo, true) AND u.rol IN ('superadmin', 'coordinador', 'observador')
        AND COALESCE(p.included, true) = v_included AND p.target_teacher_count IS NOT DISTINCT FROM v_target
    ) THEN RAISE EXCEPTION 'allocation preview is stale' USING ERRCODE = '40001'; END IF;
    FOR v_teacher_id IN SELECT value::TEXT::INTEGER FROM jsonb_array_elements(v_item.value -> 'proposed_teacher_ids') LOOP
      IF NOT EXISTS (
        SELECT 1 FROM public.docentes d WHERE d.id = v_teacher_id AND d.activo IS TRUE
          AND EXISTS (SELECT 1 FROM public.grupos g WHERE g.docente_id = d.id AND g.cuatrimestre_id = v_preview.cuatrimestre_id AND g.activo IS TRUE)
      ) OR EXISTS (
        SELECT 1 FROM public.observation_teacher_assignments a WHERE a.docente_id = v_teacher_id AND a.cuatrimestre_id = v_preview.cuatrimestre_id AND a.revoked_at IS NULL
      ) THEN RAISE EXCEPTION 'allocation preview is stale' USING ERRCODE = '40001'; END IF;
      v_planned := v_planned + 1;
      INSERT INTO public.observation_teacher_assignments (evaluator_id, docente_id, cuatrimestre_id, assigned_by, source)
        VALUES (v_evaluator_id, v_teacher_id, v_preview.cuatrimestre_id, auth.uid(), 'automatic_allocation')
        ON CONFLICT (evaluator_id, docente_id, cuatrimestre_id) WHERE revoked_at IS NULL DO NOTHING;
      GET DIAGNOSTICS v_row_count = ROW_COUNT; v_inserted := v_inserted + v_row_count;
    END LOOP;
  END LOOP;
  IF v_inserted <> v_planned THEN RAISE EXCEPTION 'allocation preview is stale' USING ERRCODE = '40001'; END IF;
  INSERT INTO public.observation_allocation_runs (preview_id, cuatrimestre_id, seed, initiated_by, counts)
    VALUES (v_preview.id, v_preview.cuatrimestre_id, v_preview.seed, auth.uid(),
      jsonb_build_object('assigned_count', v_inserted, 'evaluator_counts', v_preview.summary))
    RETURNING * INTO v_run;
  UPDATE public.observation_allocation_previews SET confirmed_at = now(), confirmed_by = auth.uid() WHERE id = v_preview.id;
  PERFORM public.audit_write_event(auth.uid(), 'superadmin', 'admin.observation_allocation', 'observation_allocation.confirmed', NULL,
    'observation_allocation_runs', jsonb_build_object('cuatrimestre_id', v_preview.cuatrimestre_id), 'insert',
    '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, jsonb_build_object('cuatrimestre_id', v_preview.cuatrimestre_id, 'assigned_count', v_inserted));
  RETURN jsonb_build_object('run_id', v_run.id, 'already_confirmed', false, 'assigned_count', v_inserted, 'evaluator_counts', v_preview.summary);
END;
$function$;

-- Extend the test-cycle FK closure in the same migration as the new FKs.
CREATE OR REPLACE FUNCTION public.test_cycle_assert_known_dependencies()
RETURNS VOID LANGUAGE plpgsql STABLE SET search_path TO '' AS $function$
DECLARE v_unknown TEXT; v_unscoped TEXT;
  v_allowed TEXT[] := ARRAY['autodiagnosticos','autoevaluacion_docente','calificacion_final_docente','calificaciones_finales','coordinador_docentes','coordinated_teacher_assignments','observation_teacher_assignments','teacher_assignment_backfill_review','observation_allocation_preferences','observation_allocation_previews','observation_allocation_runs','docente_360_feedback','docente_modalidad_historica','encuesta_control_envio','encuesta_estudiantil','encuesta_estudiantil_respuestas','evaluacion_coordinacion','evaluacion_planeacion','grupos','import_issues','import_runs','inscripciones','institutional_notices','observacion_clase','observaciones','planeaciones','planning_submission_windows'];
BEGIN
  WITH RECURSIVE dependencies(relid) AS (SELECT 'public.cuatrimestres'::regclass::oid UNION SELECT con.conrelid FROM pg_catalog.pg_constraint con JOIN dependencies d ON d.relid = con.confrelid WHERE con.contype = 'f'), tables AS (SELECT DISTINCT c.oid, c.relname FROM dependencies d JOIN pg_catalog.pg_class c ON c.oid = d.relid JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname <> 'cuatrimestres') SELECT string_agg(relname, ', ' ORDER BY relname) INTO v_unknown FROM tables WHERE NOT (relname = ANY(v_allowed));
  IF v_unknown IS NOT NULL THEN RAISE EXCEPTION 'test cycle dependency guard blocked deletion' USING ERRCODE = 'TC004'; END IF;
  WITH RECURSIVE dependencies(relid) AS (SELECT 'public.cuatrimestres'::regclass::oid UNION SELECT con.conrelid FROM pg_catalog.pg_constraint con JOIN dependencies d ON d.relid = con.confrelid WHERE con.contype = 'f') SELECT string_agg(c.relname, ', ' ORDER BY c.relname) INTO v_unscoped FROM dependencies d JOIN pg_catalog.pg_class c ON c.oid = d.relid JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname <> 'cuatrimestres' AND public.test_cycle_scope_predicate(c.relname) IS NULL;
  IF v_unscoped IS NOT NULL THEN RAISE EXCEPTION 'test cycle dependency guard blocked deletion' USING ERRCODE = 'TC004'; END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.test_cycle_deletion_preview(p_cuatrimestre_id INTEGER)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO '' AS $function$
DECLARE v_cycle public.cuatrimestres%ROWTYPE; v_table TEXT; v_counts JSONB := '{}'::jsonb;
  v_tables TEXT[] := ARRAY['autodiagnosticos','autoevaluacion_docente','calificacion_final_docente','calificaciones_finales','coordinador_docentes','coordinated_teacher_assignments','observation_teacher_assignments','teacher_assignment_backfill_review','observation_allocation_preferences','observation_allocation_previews','observation_allocation_runs','docente_360_feedback','docente_modalidad_historica','encuesta_control_envio','encuesta_estudiantil','encuesta_estudiantil_respuestas','evaluacion_coordinacion','evaluacion_planeacion','grupos','import_issues','import_runs','inscripciones','institutional_notices','observacion_clase','observaciones','planeaciones','planning_submission_windows'];
BEGIN
  IF NOT public.audit_is_superadmin() THEN RAISE EXCEPTION 'superadmin required' USING ERRCODE = '42501'; END IF;
  IF p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 THEN RAISE EXCEPTION 'valid cycle required' USING ERRCODE = '22023'; END IF;
  SELECT * INTO v_cycle FROM public.cuatrimestres WHERE id = p_cuatrimestre_id; IF NOT FOUND THEN RAISE EXCEPTION 'test cycle not found' USING ERRCODE = 'TC005'; END IF;
  PERFORM public.test_cycle_assert_deletable(v_cycle); PERFORM public.test_cycle_assert_known_dependencies();
  FOREACH v_table IN ARRAY v_tables LOOP IF to_regclass('public.' || v_table) IS NOT NULL THEN v_counts := v_counts || jsonb_build_object(v_table, public.test_cycle_count_rows(v_table, p_cuatrimestre_id)); END IF; END LOOP;
  RETURN jsonb_build_object('cycle_id', v_cycle.id, 'cycle_label', public.test_cycle_label(v_cycle), 'counts', v_counts, 'audit_events_retained', true, 'storage_cleanup_pending', (SELECT count(*) FROM public.test_cycle_storage_cleanup s WHERE s.deleted_cycle_id = p_cuatrimestre_id AND s.status = 'pending'));
END;
$function$;

CREATE OR REPLACE FUNCTION public.delete_test_cycle(p_cuatrimestre_id INTEGER, p_confirmation TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $function$
DECLARE v_cycle public.cuatrimestres%ROWTYPE; v_table TEXT; v_counts JSONB := '{}'::jsonb; v_role TEXT; v_audit_suppression_token UUID;
  v_tables TEXT[] := ARRAY['autodiagnosticos','autoevaluacion_docente','calificacion_final_docente','calificaciones_finales','coordinador_docentes','coordinated_teacher_assignments','observation_teacher_assignments','teacher_assignment_backfill_review','observation_allocation_preferences','observation_allocation_previews','observation_allocation_runs','docente_360_feedback','docente_modalidad_historica','encuesta_control_envio','encuesta_estudiantil','encuesta_estudiantil_respuestas','evaluacion_coordinacion','evaluacion_planeacion','grupos','import_issues','import_runs','inscripciones','institutional_notices','observacion_clase','observaciones','planeaciones','planning_submission_windows'];
BEGIN
  IF NOT public.audit_is_superadmin() THEN RAISE EXCEPTION 'superadmin required' USING ERRCODE = '42501'; END IF;
  IF p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 THEN RAISE EXCEPTION 'valid cycle required' USING ERRCODE = '22023'; END IF;
  SELECT * INTO v_cycle FROM public.cuatrimestres WHERE id = p_cuatrimestre_id FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'test cycle not found' USING ERRCODE = 'TC005'; END IF;
  PERFORM public.test_cycle_assert_deletable(v_cycle, p_confirmation); PERFORM public.test_cycle_assert_known_dependencies();
  IF to_regclass('public.planeaciones') IS NOT NULL THEN INSERT INTO public.test_cycle_storage_cleanup (deleted_cycle_id, cycle_label, bucket, object_reference, reference_kind) SELECT v_cycle.id, public.test_cycle_label(v_cycle), 'planeaciones', p.url_pdf, 'url' FROM public.planeaciones p WHERE p.cuatrimestre_id = v_cycle.id AND NULLIF(trim(COALESCE(p.url_pdf, '')), '') IS NOT NULL ON CONFLICT (deleted_cycle_id, bucket, object_reference) DO NOTHING; END IF;
  IF to_regclass('public.institutional_notices') IS NOT NULL THEN INSERT INTO public.test_cycle_storage_cleanup (deleted_cycle_id, cycle_label, bucket, object_reference, reference_kind) SELECT v_cycle.id, public.test_cycle_label(v_cycle), 'avisos', n.image_path, 'path' FROM public.institutional_notices n WHERE n.cuatrimestre_id = v_cycle.id AND n.image_path IS NOT NULL ON CONFLICT (deleted_cycle_id, bucket, object_reference) DO NOTHING; END IF;
  FOREACH v_table IN ARRAY v_tables LOOP IF to_regclass('public.' || v_table) IS NOT NULL THEN v_counts := v_counts || jsonb_build_object(v_table, public.test_cycle_count_rows(v_table, v_cycle.id)); END IF; END LOOP;
  SELECT u.rol INTO v_role FROM public.usuarios u WHERE u.id = auth.uid(); PERFORM public.audit_write_event(auth.uid(), v_role, 'admin.test_cycle', 'test_cycle.deleted', NULL, 'cuatrimestres', jsonb_build_object('cycle_id', v_cycle.id), 'delete', '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, jsonb_build_object('cycle_id', v_cycle.id, 'cycle_label', public.test_cycle_label(v_cycle), 'operational_counts', v_counts, 'audit_events_retained', true));
  v_audit_suppression_token := extensions.gen_random_uuid(); PERFORM set_config('app.private_test_cycle_delete_audit_token', v_audit_suppression_token::TEXT, true); INSERT INTO public.test_cycle_audit_suppression_context (transaction_id, backend_pid, actor_id, token) VALUES (txid_current(), pg_backend_pid(), auth.uid(), v_audit_suppression_token);
  PERFORM public.test_cycle_delete_rows('import_issues', v_cycle.id); PERFORM public.test_cycle_delete_rows('encuesta_estudiantil_respuestas', v_cycle.id); PERFORM public.test_cycle_delete_rows('encuesta_control_envio', v_cycle.id); IF to_regclass('public.encuesta_estudiantil') IS NOT NULL THEN PERFORM public.test_cycle_delete_rows('encuesta_estudiantil', v_cycle.id); END IF;
  PERFORM public.test_cycle_delete_rows('evaluacion_planeacion', v_cycle.id); PERFORM public.test_cycle_delete_rows('observacion_clase', v_cycle.id); PERFORM public.test_cycle_delete_rows('autoevaluacion_docente', v_cycle.id); PERFORM public.test_cycle_delete_rows('evaluacion_coordinacion', v_cycle.id); PERFORM public.test_cycle_delete_rows('observaciones', v_cycle.id); PERFORM public.test_cycle_delete_rows('planeaciones', v_cycle.id); PERFORM public.test_cycle_delete_rows('planning_submission_windows', v_cycle.id); PERFORM public.test_cycle_delete_rows('autodiagnosticos', v_cycle.id); PERFORM public.test_cycle_delete_rows('docente_360_feedback', v_cycle.id); IF to_regclass('public.calificacion_final_docente') IS NOT NULL THEN PERFORM public.test_cycle_delete_rows('calificacion_final_docente', v_cycle.id); END IF; PERFORM public.test_cycle_delete_rows('calificaciones_finales', v_cycle.id); IF to_regclass('public.docente_modalidad_historica') IS NOT NULL THEN PERFORM public.test_cycle_delete_rows('docente_modalidad_historica', v_cycle.id); END IF; PERFORM public.test_cycle_delete_rows('institutional_notices', v_cycle.id); PERFORM public.test_cycle_delete_rows('inscripciones', v_cycle.id);
  PERFORM public.test_cycle_delete_rows('observation_allocation_runs', v_cycle.id); PERFORM public.test_cycle_delete_rows('observation_allocation_previews', v_cycle.id); PERFORM public.test_cycle_delete_rows('observation_allocation_preferences', v_cycle.id); PERFORM public.test_cycle_delete_rows('teacher_assignment_backfill_review', v_cycle.id); PERFORM public.test_cycle_delete_rows('coordinated_teacher_assignments', v_cycle.id); PERFORM public.test_cycle_delete_rows('observation_teacher_assignments', v_cycle.id); PERFORM public.test_cycle_delete_rows('coordinador_docentes', v_cycle.id); PERFORM public.test_cycle_delete_rows('import_runs', v_cycle.id); PERFORM public.test_cycle_delete_rows('grupos', v_cycle.id);
  DELETE FROM public.cuatrimestres WHERE id = v_cycle.id; DELETE FROM public.test_cycle_audit_suppression_context WHERE transaction_id = txid_current() AND backend_pid = pg_backend_pid() AND actor_id = auth.uid() AND token = v_audit_suppression_token; PERFORM set_config('app.private_test_cycle_delete_audit_token', '', true); PERFORM public.refrescar_resultados_agregados();
  RETURN jsonb_build_object('cycle_id', v_cycle.id, 'cycle_label', public.test_cycle_label(v_cycle), 'counts', v_counts, 'audit_events_retained', true, 'storage_cleanup_pending', (SELECT count(*) FROM public.test_cycle_storage_cleanup s WHERE s.deleted_cycle_id = v_cycle.id AND s.status = 'pending'));
END;
$function$;

REVOKE ALL ON FUNCTION public.validate_observation_allocation_preference() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_assignment_teacher_candidates(INTEGER, TEXT, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_teacher_assignment_list_v2(INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_observation_allocation_evaluators(INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.assign_teacher_assignments(TEXT, UUID, INTEGER, INTEGER[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.revoke_teacher_assignments(TEXT, INTEGER, BIGINT[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.save_observation_allocation_preferences(INTEGER, JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.preview_observation_allocation(INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.confirm_observation_allocation(INTEGER, UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.test_cycle_assert_known_dependencies() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.test_cycle_deletion_preview(INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.delete_test_cycle(INTEGER, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_assignment_teacher_candidates(INTEGER, TEXT, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_teacher_assignment_list_v2(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_observation_allocation_evaluators(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assign_teacher_assignments(TEXT, UUID, INTEGER, INTEGER[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_teacher_assignments(TEXT, INTEGER, BIGINT[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_observation_allocation_preferences(INTEGER, JSONB) TO authenticated;
GRANT EXECUTE ON FUNCTION public.preview_observation_allocation(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.confirm_observation_allocation(INTEGER, UUID, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.test_cycle_deletion_preview(INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_test_cycle(INTEGER, TEXT) TO authenticated;

NOTIFY pgrst, 'reload schema';
