-- An explicit NP applies to all active groups a teacher has for one normalized
-- subject name in a cycle. It is deliberately separate from planeaciones: NP is
-- an administrative exception, never a synthetic planning document.
CREATE OR REPLACE FUNCTION public.normalize_planning_subject_name(p_value TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
SET search_path TO ''
AS $function$
  SELECT lower(regexp_replace(trim(translate(coalesce(p_value, ''),
    'ÁÉÍÓÚÜÑáéíóúüñ', 'AEIOUUNaeiouun')), '\s+', ' ', 'g'));
$function$;

CREATE TABLE IF NOT EXISTS public.planning_subject_np (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  docente_id INTEGER NOT NULL REFERENCES public.docentes(id),
  cuatrimestre_id INTEGER NOT NULL REFERENCES public.cuatrimestres(id),
  subject_key TEXT NOT NULL CHECK (subject_key = public.normalize_planning_subject_name(subject_key) AND subject_key <> ''),
  subject_name TEXT NOT NULL CHECK (nullif(trim(subject_name), '') IS NOT NULL),
  estado TEXT NOT NULL DEFAULT 'NP' CHECK (estado = 'NP'),
  motivo TEXT,
  marked_by UUID NOT NULL REFERENCES public.usuarios(id),
  marked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (docente_id, cuatrimestre_id, subject_key)
);

CREATE INDEX IF NOT EXISTS planning_subject_np_cycle_teacher_idx
  ON public.planning_subject_np (cuatrimestre_id, docente_id);

ALTER TABLE public.planning_subject_np ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.planning_subject_np FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.planning_subject_np TO authenticated;

-- Teachers may only read their own NP subjects; staff reads follow existing
-- coordinated-teacher assignment scope. Writes are only through the RPC below.
CREATE POLICY planning_subject_np_select_authorized
  ON public.planning_subject_np FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.usuarios u
      WHERE u.id = auth.uid() AND coalesce(u.activo, true)
        AND (u.rol = 'superadmin'
          OR (u.rol = 'docente' AND u.entidad_id = planning_subject_np.docente_id)
          OR (u.rol = 'coordinador' AND public.can_manage_coordinated_teacher(planning_subject_np.docente_id, planning_subject_np.cuatrimestre_id)))
    )
  );

CREATE OR REPLACE FUNCTION public.set_planning_subject_np(
  p_docente_id INTEGER,
  p_cuatrimestre_id INTEGER,
  p_subject_key TEXT,
  p_subject_name TEXT,
  p_motivo TEXT DEFAULT NULL,
  p_mark_np BOOLEAN DEFAULT true
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_actor UUID := auth.uid();
  v_role TEXT;
  v_key TEXT := public.normalize_planning_subject_name(p_subject_key);
  v_result JSONB;
BEGIN
  SELECT u.rol INTO v_role
  FROM public.usuarios u
  WHERE u.id = v_actor AND coalesce(u.activo, true);

  IF v_role <> 'superadmin' OR p_docente_id IS NULL OR p_docente_id <= 0
    OR p_cuatrimestre_id IS NULL OR p_cuatrimestre_id <= 0 OR v_key = ''
    OR v_key IS DISTINCT FROM p_subject_key
    OR nullif(trim(coalesce(p_subject_name, '')), '') IS NULL
    OR length(coalesce(p_motivo, '')) > 500 THEN
    RAISE EXCEPTION 'valid superadmin NP request required' USING ERRCODE = '22023';
  END IF;

  -- The API resolves the exact normalized name from the active assignment before
  -- calling this RPC. This independent check prevents orphan overrides.
  IF NOT EXISTS (
    SELECT 1 FROM public.grupos g
    JOIN public.asignaturas a ON a.id = g.asignatura_id
    WHERE g.docente_id = p_docente_id AND g.cuatrimestre_id = p_cuatrimestre_id
      AND g.activo IS TRUE
      AND g.modalidad = 'Escolarizado'
      AND public.normalize_planning_subject_name(a.nombre) = v_key
  ) THEN
    RAISE EXCEPTION 'assigned subject scope required' USING ERRCODE = '22023';
  END IF;

  IF p_mark_np AND EXISTS (
    SELECT 1 FROM public.planeaciones p
    JOIN public.asignaturas a ON a.id = p.asignatura_id
    WHERE p.docente_id = p_docente_id AND p.cuatrimestre_id = p_cuatrimestre_id
      AND p.estado = 'Aprobado'
      AND public.normalize_planning_subject_name(a.nombre) = v_key
  ) THEN
    RAISE EXCEPTION 'approved planning cannot be marked NP' USING ERRCODE = '23514';
  END IF;

  IF p_mark_np THEN
    INSERT INTO public.planning_subject_np (
      docente_id, cuatrimestre_id, subject_key, subject_name, motivo, marked_by, marked_at, updated_at
    ) VALUES (
      p_docente_id, p_cuatrimestre_id, v_key, trim(p_subject_name), nullif(trim(p_motivo), ''), v_actor, now(), now()
    ) ON CONFLICT (docente_id, cuatrimestre_id, subject_key) DO UPDATE SET
      subject_name = EXCLUDED.subject_name, motivo = EXCLUDED.motivo,
      marked_by = EXCLUDED.marked_by, marked_at = now(), updated_at = now()
    RETURNING to_jsonb(public.planning_subject_np.*) INTO v_result;
  ELSE
    DELETE FROM public.planning_subject_np
    WHERE docente_id = p_docente_id AND cuatrimestre_id = p_cuatrimestre_id AND subject_key = v_key
    RETURNING jsonb_build_object('docente_id', docente_id, 'cuatrimestre_id', cuatrimestre_id, 'subject_key', subject_key, 'estado', 'reactivated') INTO v_result;
  END IF;

  PERFORM public.audit_write_event(v_actor, v_role, 'admin.planning',
    CASE WHEN p_mark_np THEN 'planning_subject.np_marked' ELSE 'planning_subject.reactivated' END,
    NULL, 'planning_subject_np', jsonb_build_object('docente_id', p_docente_id, 'cuatrimestre_id', p_cuatrimestre_id, 'subject_key', v_key),
    CASE WHEN p_mark_np THEN 'upsert' ELSE 'delete' END, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb,
    jsonb_build_object('subject_name', trim(p_subject_name), 'reason_present', nullif(trim(p_motivo), '') IS NOT NULL));

  RETURN coalesce(v_result, jsonb_build_object('docente_id', p_docente_id, 'cuatrimestre_id', p_cuatrimestre_id, 'subject_key', v_key, 'estado', 'reactivated'));
END;
$function$;

REVOKE ALL ON FUNCTION public.normalize_planning_subject_name(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_planning_subject_np(INTEGER, INTEGER, TEXT, TEXT, TEXT, BOOLEAN) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_planning_subject_np(INTEGER, INTEGER, TEXT, TEXT, TEXT, BOOLEAN) TO authenticated;

NOTIFY pgrst, 'reload schema';
