type Neighborhood @table {
  name: String!
  city: String!
  zipCode: String!
}

type User @table {
  name: String!
  email: String!
  address: String!
  neighborhood: Neighborhood!
  phoneNumber: String
  bio: String
}

type Post @table {
  user: User!
  neighborhood: Neighborhood!
  title: String!
  content: String!
  type: String!
  imageUrl: String
  expiresAt: Timestamp
}

type Item @table {
  owner: User!
  name: String!
  status: String!
  description: String
  category: String
}

type Message @table {
  sender: User!
  receiver: User!
  content: String!
  timestamp: Timestamp!
}